/**
 * EL CALENDARIO DE LA LIGA, TAL CUAL, PARA LA QUINIELA.
 *
 * Sale del Excel que trajo el cuerpo técnico —Primera RFEF, grupo 2, 26/27—,
 * volcado UNA vez a código: son treinta y ocho jornadas que no cambian en toda
 * la temporada, y leer un .xlsx en caliente para algo que es fijo sería pagar
 * una lectura de disco y un descomprimido en cada visita.
 *
 * Aquí **no hay pronósticos ni resultados**: el Excel venía sólo con el
 * calendario y las iniciales de los diez que juegan. Lo que se rellena cada
 * semana vive en Supabase, no aquí.
 *
 * 380 partidos · 20 equipos · jornadas 1-38.
 */

export type PartidoQuiniela = {
  jornada: number;
  /** "2026-08-30": se ordena sola y no depende del huso. */
  fecha: string;
  local: string;
  visitante: string;
};

export const CALENDARIO: PartidoQuiniela[] = [
  { jornada: 1, fecha: "2026-08-30", local: "Águilas FC", visitante: "AD Alcorcón" },
  { jornada: 1, fecha: "2026-08-30", local: "Algeciras CF", visitante: "FC Cartagena" },
  { jornada: 1, fecha: "2026-08-30", local: "Atlético Madrileño", visitante: "Juventud de Torremolinos CF" },
  { jornada: 1, fecha: "2026-08-30", local: "Antequera CF", visitante: "UD Ibiza" },
  { jornada: 1, fecha: "2026-08-30", local: "CE Europa", visitante: "Real Jaén CF" },
  { jornada: 1, fecha: "2026-08-30", local: "Hércules de Alicante CF", visitante: "Real Murcia CF" },
  { jornada: 1, fecha: "2026-08-30", local: "SD Huesca", visitante: "UE Sant Andreu" },
  { jornada: 1, fecha: "2026-08-30", local: "CF Rayo Majadahonda", visitante: "Villarreal CF \"B\"" },
  { jornada: 1, fecha: "2026-08-30", local: "Gimnàstic de Tarragona", visitante: "Real Zaragoza" },
  { jornada: 1, fecha: "2026-08-30", local: "CD Teruel", visitante: "Real Madrid Castilla" },
  { jornada: 2, fecha: "2026-09-06", local: "AD Alcorcón", visitante: "CE Europa" },
  { jornada: 2, fecha: "2026-09-06", local: "FC Cartagena", visitante: "Gimnàstic de Tarragona" },
  { jornada: 2, fecha: "2026-09-06", local: "Hércules de Alicante CF", visitante: "Atlético Madrileño" },
  { jornada: 2, fecha: "2026-09-06", local: "UD Ibiza", visitante: "CF Rayo Majadahonda" },
  { jornada: 2, fecha: "2026-09-06", local: "Real Jaén CF", visitante: "SD Huesca" },
  { jornada: 2, fecha: "2026-09-06", local: "Real Murcia CF", visitante: "CD Teruel" },
  { jornada: 2, fecha: "2026-09-06", local: "Real Madrid Castilla", visitante: "Juventud de Torremolinos CF" },
  { jornada: 2, fecha: "2026-09-06", local: "UE Sant Andreu", visitante: "Águilas FC" },
  { jornada: 2, fecha: "2026-09-06", local: "Villarreal CF \"B\"", visitante: "Algeciras CF" },
  { jornada: 2, fecha: "2026-09-06", local: "Real Zaragoza", visitante: "Antequera CF" },
  { jornada: 3, fecha: "2026-09-13", local: "Águilas FC", visitante: "Real Madrid Castilla" },
  { jornada: 3, fecha: "2026-09-13", local: "Atlético Madrileño", visitante: "Real Murcia CF" },
  { jornada: 3, fecha: "2026-09-13", local: "Antequera CF", visitante: "AD Alcorcón" },
  { jornada: 3, fecha: "2026-09-13", local: "CE Europa", visitante: "Hércules de Alicante CF" },
  { jornada: 3, fecha: "2026-09-13", local: "SD Huesca", visitante: "Villarreal CF \"B\"" },
  { jornada: 3, fecha: "2026-09-13", local: "UD Ibiza", visitante: "UE Sant Andreu" },
  { jornada: 3, fecha: "2026-09-13", local: "Juventud de Torremolinos CF", visitante: "Real Zaragoza" },
  { jornada: 3, fecha: "2026-09-13", local: "CF Rayo Majadahonda", visitante: "FC Cartagena" },
  { jornada: 3, fecha: "2026-09-13", local: "Gimnàstic de Tarragona", visitante: "Algeciras CF" },
  { jornada: 3, fecha: "2026-09-13", local: "CD Teruel", visitante: "Real Jaén CF" },
  { jornada: 4, fecha: "2026-09-20", local: "AD Alcorcón", visitante: "Gimnàstic de Tarragona" },
  { jornada: 4, fecha: "2026-09-20", local: "Algeciras CF", visitante: "Águilas FC" },
  { jornada: 4, fecha: "2026-09-20", local: "Hércules de Alicante CF", visitante: "Juventud de Torremolinos CF" },
  { jornada: 4, fecha: "2026-09-20", local: "SD Huesca", visitante: "Atlético Madrileño" },
  { jornada: 4, fecha: "2026-09-20", local: "Real Jaén CF", visitante: "UD Ibiza" },
  { jornada: 4, fecha: "2026-09-20", local: "CF Rayo Majadahonda", visitante: "CD Teruel" },
  { jornada: 4, fecha: "2026-09-20", local: "Real Murcia CF", visitante: "CE Europa" },
  { jornada: 4, fecha: "2026-09-20", local: "UE Sant Andreu", visitante: "Real Madrid Castilla" },
  { jornada: 4, fecha: "2026-09-20", local: "Villarreal CF \"B\"", visitante: "Antequera CF" },
  { jornada: 4, fecha: "2026-09-20", local: "Real Zaragoza", visitante: "FC Cartagena" },
  { jornada: 5, fecha: "2026-09-27", local: "Águilas FC", visitante: "Hércules de Alicante CF" },
  { jornada: 5, fecha: "2026-09-27", local: "Atlético Madrileño", visitante: "Villarreal CF \"B\"" },
  { jornada: 5, fecha: "2026-09-27", local: "Antequera CF", visitante: "Real Jaén CF" },
  { jornada: 5, fecha: "2026-09-27", local: "FC Cartagena", visitante: "Real Murcia CF" },
  { jornada: 5, fecha: "2026-09-27", local: "CE Europa", visitante: "CF Rayo Majadahonda" },
  { jornada: 5, fecha: "2026-09-27", local: "UD Ibiza", visitante: "Real Zaragoza" },
  { jornada: 5, fecha: "2026-09-27", local: "Juventud de Torremolinos CF", visitante: "Algeciras CF" },
  { jornada: 5, fecha: "2026-09-27", local: "Gimnàstic de Tarragona", visitante: "UE Sant Andreu" },
  { jornada: 5, fecha: "2026-09-27", local: "Real Madrid Castilla", visitante: "AD Alcorcón" },
  { jornada: 5, fecha: "2026-09-27", local: "CD Teruel", visitante: "SD Huesca" },
  { jornada: 6, fecha: "2026-10-04", local: "AD Alcorcón", visitante: "Juventud de Torremolinos CF" },
  { jornada: 6, fecha: "2026-10-04", local: "Algeciras CF", visitante: "CF Rayo Majadahonda" },
  { jornada: 6, fecha: "2026-10-04", local: "FC Cartagena", visitante: "Águilas FC" },
  { jornada: 6, fecha: "2026-10-04", local: "Hércules de Alicante CF", visitante: "Real Jaén CF" },
  { jornada: 6, fecha: "2026-10-04", local: "SD Huesca", visitante: "CE Europa" },
  { jornada: 6, fecha: "2026-10-04", local: "Real Murcia CF", visitante: "Gimnàstic de Tarragona" },
  { jornada: 6, fecha: "2026-10-04", local: "Real Madrid Castilla", visitante: "Atlético Madrileño" },
  { jornada: 6, fecha: "2026-10-04", local: "UE Sant Andreu", visitante: "Antequera CF" },
  { jornada: 6, fecha: "2026-10-04", local: "Villarreal CF \"B\"", visitante: "UD Ibiza" },
  { jornada: 6, fecha: "2026-10-04", local: "Real Zaragoza", visitante: "CD Teruel" },
  { jornada: 7, fecha: "2026-10-11", local: "Águilas FC", visitante: "SD Huesca" },
  { jornada: 7, fecha: "2026-10-11", local: "Atlético Madrileño", visitante: "Real Zaragoza" },
  { jornada: 7, fecha: "2026-10-11", local: "Antequera CF", visitante: "FC Cartagena" },
  { jornada: 7, fecha: "2026-10-11", local: "CE Europa", visitante: "Algeciras CF" },
  { jornada: 7, fecha: "2026-10-11", local: "Hércules de Alicante CF", visitante: "UE Sant Andreu" },
  { jornada: 7, fecha: "2026-10-11", local: "UD Ibiza", visitante: "Real Madrid Castilla" },
  { jornada: 7, fecha: "2026-10-11", local: "Real Jaén CF", visitante: "Villarreal CF \"B\"" },
  { jornada: 7, fecha: "2026-10-11", local: "Juventud de Torremolinos CF", visitante: "Gimnàstic de Tarragona" },
  { jornada: 7, fecha: "2026-10-11", local: "CF Rayo Majadahonda", visitante: "Real Murcia CF" },
  { jornada: 7, fecha: "2026-10-11", local: "CD Teruel", visitante: "AD Alcorcón" },
  { jornada: 8, fecha: "2026-10-18", local: "AD Alcorcón", visitante: "SD Huesca" },
  { jornada: 8, fecha: "2026-10-18", local: "Águilas FC", visitante: "UD Ibiza" },
  { jornada: 8, fecha: "2026-10-18", local: "Algeciras CF", visitante: "Hércules de Alicante CF" },
  { jornada: 8, fecha: "2026-10-18", local: "FC Cartagena", visitante: "CE Europa" },
  { jornada: 8, fecha: "2026-10-18", local: "Real Jaén CF", visitante: "CF Rayo Majadahonda" },
  { jornada: 8, fecha: "2026-10-18", local: "Real Murcia CF", visitante: "Real Zaragoza" },
  { jornada: 8, fecha: "2026-10-18", local: "Gimnàstic de Tarragona", visitante: "Atlético Madrileño" },
  { jornada: 8, fecha: "2026-10-18", local: "Real Madrid Castilla", visitante: "Antequera CF" },
  { jornada: 8, fecha: "2026-10-18", local: "UE Sant Andreu", visitante: "Juventud de Torremolinos CF" },
  { jornada: 8, fecha: "2026-10-18", local: "Villarreal CF \"B\"", visitante: "CD Teruel" },
  { jornada: 9, fecha: "2026-10-25", local: "AD Alcorcón", visitante: "UD Ibiza" },
  { jornada: 9, fecha: "2026-10-25", local: "Algeciras CF", visitante: "Real Madrid Castilla" },
  { jornada: 9, fecha: "2026-10-25", local: "Atlético Madrileño", visitante: "Real Jaén CF" },
  { jornada: 9, fecha: "2026-10-25", local: "CE Europa", visitante: "Real Zaragoza" },
  { jornada: 9, fecha: "2026-10-25", local: "SD Huesca", visitante: "Antequera CF" },
  { jornada: 9, fecha: "2026-10-25", local: "Juventud de Torremolinos CF", visitante: "Real Murcia CF" },
  { jornada: 9, fecha: "2026-10-25", local: "CF Rayo Majadahonda", visitante: "UE Sant Andreu" },
  { jornada: 9, fecha: "2026-10-25", local: "Gimnàstic de Tarragona", visitante: "Hércules de Alicante CF" },
  { jornada: 9, fecha: "2026-10-25", local: "CD Teruel", visitante: "Águilas FC" },
  { jornada: 9, fecha: "2026-10-25", local: "Villarreal CF \"B\"", visitante: "FC Cartagena" },
  { jornada: 10, fecha: "2026-11-01", local: "Atlético Madrileño", visitante: "AD Alcorcón" },
  { jornada: 10, fecha: "2026-11-01", local: "Antequera CF", visitante: "Real Murcia CF" },
  { jornada: 10, fecha: "2026-11-01", local: "Hércules de Alicante CF", visitante: "CF Rayo Majadahonda" },
  { jornada: 10, fecha: "2026-11-01", local: "SD Huesca", visitante: "Gimnàstic de Tarragona" },
  { jornada: 10, fecha: "2026-11-01", local: "UD Ibiza", visitante: "CE Europa" },
  { jornada: 10, fecha: "2026-11-01", local: "Real Jaén CF", visitante: "Algeciras CF" },
  { jornada: 10, fecha: "2026-11-01", local: "Juventud de Torremolinos CF", visitante: "Águilas FC" },
  { jornada: 10, fecha: "2026-11-01", local: "Real Madrid Castilla", visitante: "FC Cartagena" },
  { jornada: 10, fecha: "2026-11-01", local: "UE Sant Andreu", visitante: "CD Teruel" },
  { jornada: 10, fecha: "2026-11-01", local: "Real Zaragoza", visitante: "Villarreal CF \"B\"" },
  { jornada: 11, fecha: "2026-11-08", local: "AD Alcorcón", visitante: "Real Jaén CF" },
  { jornada: 11, fecha: "2026-11-08", local: "Águilas FC", visitante: "Gimnàstic de Tarragona" },
  { jornada: 11, fecha: "2026-11-08", local: "Antequera CF", visitante: "CF Rayo Majadahonda" },
  { jornada: 11, fecha: "2026-11-08", local: "FC Cartagena", visitante: "UE Sant Andreu" },
  { jornada: 11, fecha: "2026-11-08", local: "CE Europa", visitante: "Atlético Madrileño" },
  { jornada: 11, fecha: "2026-11-08", local: "Real Murcia CF", visitante: "Algeciras CF" },
  { jornada: 11, fecha: "2026-11-08", local: "Real Madrid Castilla", visitante: "Hércules de Alicante CF" },
  { jornada: 11, fecha: "2026-11-08", local: "CD Teruel", visitante: "UD Ibiza" },
  { jornada: 11, fecha: "2026-11-08", local: "Villarreal CF \"B\"", visitante: "Juventud de Torremolinos CF" },
  { jornada: 11, fecha: "2026-11-08", local: "Real Zaragoza", visitante: "SD Huesca" },
  { jornada: 12, fecha: "2026-11-15", local: "Algeciras CF", visitante: "Antequera CF" },
  { jornada: 12, fecha: "2026-11-15", local: "Atlético Madrileño", visitante: "CD Teruel" },
  { jornada: 12, fecha: "2026-11-15", local: "CE Europa", visitante: "UE Sant Andreu" },
  { jornada: 12, fecha: "2026-11-15", local: "Hércules de Alicante CF", visitante: "Villarreal CF \"B\"" },
  { jornada: 12, fecha: "2026-11-15", local: "UD Ibiza", visitante: "FC Cartagena" },
  { jornada: 12, fecha: "2026-11-15", local: "Real Jaén CF", visitante: "Real Zaragoza" },
  { jornada: 12, fecha: "2026-11-15", local: "Juventud de Torremolinos CF", visitante: "SD Huesca" },
  { jornada: 12, fecha: "2026-11-15", local: "CF Rayo Majadahonda", visitante: "Águilas FC" },
  { jornada: 12, fecha: "2026-11-15", local: "Real Murcia CF", visitante: "AD Alcorcón" },
  { jornada: 12, fecha: "2026-11-15", local: "Gimnàstic de Tarragona", visitante: "Real Madrid Castilla" },
  { jornada: 13, fecha: "2026-11-22", local: "AD Alcorcón", visitante: "Algeciras CF" },
  { jornada: 13, fecha: "2026-11-22", local: "Águilas FC", visitante: "CE Europa" },
  { jornada: 13, fecha: "2026-11-22", local: "Antequera CF", visitante: "Juventud de Torremolinos CF" },
  { jornada: 13, fecha: "2026-11-22", local: "FC Cartagena", visitante: "Real Jaén CF" },
  { jornada: 13, fecha: "2026-11-22", local: "SD Huesca", visitante: "UD Ibiza" },
  { jornada: 13, fecha: "2026-11-22", local: "Real Madrid Castilla", visitante: "Real Murcia CF" },
  { jornada: 13, fecha: "2026-11-22", local: "CD Teruel", visitante: "Hércules de Alicante CF" },
  { jornada: 13, fecha: "2026-11-22", local: "UE Sant Andreu", visitante: "Atlético Madrileño" },
  { jornada: 13, fecha: "2026-11-22", local: "Villarreal CF \"B\"", visitante: "Gimnàstic de Tarragona" },
  { jornada: 13, fecha: "2026-11-22", local: "Real Zaragoza", visitante: "CF Rayo Majadahonda" },
  { jornada: 14, fecha: "2026-11-29", local: "AD Alcorcón", visitante: "Real Zaragoza" },
  { jornada: 14, fecha: "2026-11-29", local: "Algeciras CF", visitante: "SD Huesca" },
  { jornada: 14, fecha: "2026-11-29", local: "CE Europa", visitante: "Villarreal CF \"B\"" },
  { jornada: 14, fecha: "2026-11-29", local: "Hércules de Alicante CF", visitante: "Antequera CF" },
  { jornada: 14, fecha: "2026-11-29", local: "UD Ibiza", visitante: "Atlético Madrileño" },
  { jornada: 14, fecha: "2026-11-29", local: "Real Jaén CF", visitante: "Águilas FC" },
  { jornada: 14, fecha: "2026-11-29", local: "Juventud de Torremolinos CF", visitante: "FC Cartagena" },
  { jornada: 14, fecha: "2026-11-29", local: "CF Rayo Majadahonda", visitante: "Real Madrid Castilla" },
  { jornada: 14, fecha: "2026-11-29", local: "Real Murcia CF", visitante: "UE Sant Andreu" },
  { jornada: 14, fecha: "2026-11-29", local: "Gimnàstic de Tarragona", visitante: "CD Teruel" },
  { jornada: 15, fecha: "2026-12-06", local: "Atlético Madrileño", visitante: "CF Rayo Majadahonda" },
  { jornada: 15, fecha: "2026-12-06", local: "Antequera CF", visitante: "CE Europa" },
  { jornada: 15, fecha: "2026-12-06", local: "FC Cartagena", visitante: "Hércules de Alicante CF" },
  { jornada: 15, fecha: "2026-12-06", local: "SD Huesca", visitante: "Real Murcia CF" },
  { jornada: 15, fecha: "2026-12-06", local: "UD Ibiza", visitante: "Gimnàstic de Tarragona" },
  { jornada: 15, fecha: "2026-12-06", local: "Real Madrid Castilla", visitante: "Real Jaén CF" },
  { jornada: 15, fecha: "2026-12-06", local: "CD Teruel", visitante: "Juventud de Torremolinos CF" },
  { jornada: 15, fecha: "2026-12-06", local: "UE Sant Andreu", visitante: "Algeciras CF" },
  { jornada: 15, fecha: "2026-12-06", local: "Villarreal CF \"B\"", visitante: "AD Alcorcón" },
  { jornada: 15, fecha: "2026-12-06", local: "Real Zaragoza", visitante: "Águilas FC" },
  { jornada: 16, fecha: "2026-12-13", local: "Águilas FC", visitante: "Villarreal CF \"B\"" },
  { jornada: 16, fecha: "2026-12-13", local: "Algeciras CF", visitante: "CD Teruel" },
  { jornada: 16, fecha: "2026-12-13", local: "FC Cartagena", visitante: "Atlético Madrileño" },
  { jornada: 16, fecha: "2026-12-13", local: "Hércules de Alicante CF", visitante: "UD Ibiza" },
  { jornada: 16, fecha: "2026-12-13", local: "Juventud de Torremolinos CF", visitante: "CE Europa" },
  { jornada: 16, fecha: "2026-12-13", local: "CF Rayo Majadahonda", visitante: "SD Huesca" },
  { jornada: 16, fecha: "2026-12-13", local: "Real Murcia CF", visitante: "Real Jaén CF" },
  { jornada: 16, fecha: "2026-12-13", local: "Gimnàstic de Tarragona", visitante: "Antequera CF" },
  { jornada: 16, fecha: "2026-12-13", local: "Real Madrid Castilla", visitante: "Real Zaragoza" },
  { jornada: 16, fecha: "2026-12-13", local: "UE Sant Andreu", visitante: "AD Alcorcón" },
  { jornada: 17, fecha: "2026-12-20", local: "AD Alcorcón", visitante: "CF Rayo Majadahonda" },
  { jornada: 17, fecha: "2026-12-20", local: "Atlético Madrileño", visitante: "Algeciras CF" },
  { jornada: 17, fecha: "2026-12-20", local: "Antequera CF", visitante: "Águilas FC" },
  { jornada: 17, fecha: "2026-12-20", local: "CE Europa", visitante: "Gimnàstic de Tarragona" },
  { jornada: 17, fecha: "2026-12-20", local: "SD Huesca", visitante: "Real Madrid Castilla" },
  { jornada: 17, fecha: "2026-12-20", local: "UD Ibiza", visitante: "Real Murcia CF" },
  { jornada: 17, fecha: "2026-12-20", local: "Real Jaén CF", visitante: "Juventud de Torremolinos CF" },
  { jornada: 17, fecha: "2026-12-20", local: "CD Teruel", visitante: "FC Cartagena" },
  { jornada: 17, fecha: "2026-12-20", local: "Villarreal CF \"B\"", visitante: "UE Sant Andreu" },
  { jornada: 17, fecha: "2026-12-20", local: "Real Zaragoza", visitante: "Hércules de Alicante CF" },
  { jornada: 18, fecha: "2027-01-03", local: "Águilas FC", visitante: "Atlético Madrileño" },
  { jornada: 18, fecha: "2027-01-03", local: "Algeciras CF", visitante: "Real Zaragoza" },
  { jornada: 18, fecha: "2027-01-03", local: "FC Cartagena", visitante: "SD Huesca" },
  { jornada: 18, fecha: "2027-01-03", local: "Hércules de Alicante CF", visitante: "AD Alcorcón" },
  { jornada: 18, fecha: "2027-01-03", local: "Juventud de Torremolinos CF", visitante: "UD Ibiza" },
  { jornada: 18, fecha: "2027-01-03", local: "Real Murcia CF", visitante: "Villarreal CF \"B\"" },
  { jornada: 18, fecha: "2027-01-03", local: "Gimnàstic de Tarragona", visitante: "CF Rayo Majadahonda" },
  { jornada: 18, fecha: "2027-01-03", local: "Real Madrid Castilla", visitante: "CE Europa" },
  { jornada: 18, fecha: "2027-01-03", local: "CD Teruel", visitante: "Antequera CF" },
  { jornada: 18, fecha: "2027-01-03", local: "UE Sant Andreu", visitante: "Real Jaén CF" },
  { jornada: 19, fecha: "2027-01-10", local: "AD Alcorcón", visitante: "FC Cartagena" },
  { jornada: 19, fecha: "2027-01-10", local: "Antequera CF", visitante: "Atlético Madrileño" },
  { jornada: 19, fecha: "2027-01-10", local: "CE Europa", visitante: "CD Teruel" },
  { jornada: 19, fecha: "2027-01-10", local: "SD Huesca", visitante: "Hércules de Alicante CF" },
  { jornada: 19, fecha: "2027-01-10", local: "UD Ibiza", visitante: "Algeciras CF" },
  { jornada: 19, fecha: "2027-01-10", local: "Real Jaén CF", visitante: "Gimnàstic de Tarragona" },
  { jornada: 19, fecha: "2027-01-10", local: "CF Rayo Majadahonda", visitante: "Juventud de Torremolinos CF" },
  { jornada: 19, fecha: "2027-01-10", local: "Real Murcia CF", visitante: "Águilas FC" },
  { jornada: 19, fecha: "2027-01-10", local: "Villarreal CF \"B\"", visitante: "Real Madrid Castilla" },
  { jornada: 19, fecha: "2027-01-10", local: "Real Zaragoza", visitante: "UE Sant Andreu" },
  { jornada: 20, fecha: "2027-01-17", local: "Águilas FC", visitante: "Juventud de Torremolinos CF" },
  { jornada: 20, fecha: "2027-01-17", local: "Atlético Madrileño", visitante: "SD Huesca" },
  { jornada: 20, fecha: "2027-01-17", local: "FC Cartagena", visitante: "CF Rayo Majadahonda" },
  { jornada: 20, fecha: "2027-01-17", local: "Hércules de Alicante CF", visitante: "CE Europa" },
  { jornada: 20, fecha: "2027-01-17", local: "Real Jaén CF", visitante: "Antequera CF" },
  { jornada: 20, fecha: "2027-01-17", local: "Gimnàstic de Tarragona", visitante: "AD Alcorcón" },
  { jornada: 20, fecha: "2027-01-17", local: "Real Madrid Castilla", visitante: "Algeciras CF" },
  { jornada: 20, fecha: "2027-01-17", local: "CD Teruel", visitante: "Villarreal CF \"B\"" },
  { jornada: 20, fecha: "2027-01-17", local: "UE Sant Andreu", visitante: "UD Ibiza" },
  { jornada: 20, fecha: "2027-01-17", local: "Real Zaragoza", visitante: "Real Murcia CF" },
  { jornada: 21, fecha: "2027-01-24", local: "AD Alcorcón", visitante: "CD Teruel" },
  { jornada: 21, fecha: "2027-01-24", local: "Algeciras CF", visitante: "Gimnàstic de Tarragona" },
  { jornada: 21, fecha: "2027-01-24", local: "Antequera CF", visitante: "Real Madrid Castilla" },
  { jornada: 21, fecha: "2027-01-24", local: "SD Huesca", visitante: "Real Jaén CF" },
  { jornada: 21, fecha: "2027-01-24", local: "UD Ibiza", visitante: "Águilas FC" },
  { jornada: 21, fecha: "2027-01-24", local: "Juventud de Torremolinos CF", visitante: "Hércules de Alicante CF" },
  { jornada: 21, fecha: "2027-01-24", local: "CF Rayo Majadahonda", visitante: "CE Europa" },
  { jornada: 21, fecha: "2027-01-24", local: "Real Murcia CF", visitante: "Atlético Madrileño" },
  { jornada: 21, fecha: "2027-01-24", local: "UE Sant Andreu", visitante: "FC Cartagena" },
  { jornada: 21, fecha: "2027-01-24", local: "Villarreal CF \"B\"", visitante: "Real Zaragoza" },
  { jornada: 22, fecha: "2027-01-31", local: "Águilas FC", visitante: "Algeciras CF" },
  { jornada: 22, fecha: "2027-01-31", local: "Atlético Madrileño", visitante: "Hércules de Alicante CF" },
  { jornada: 22, fecha: "2027-01-31", local: "Antequera CF", visitante: "Villarreal CF \"B\"" },
  { jornada: 22, fecha: "2027-01-31", local: "FC Cartagena", visitante: "UD Ibiza" },
  { jornada: 22, fecha: "2027-01-31", local: "CE Europa", visitante: "Real Murcia CF" },
  { jornada: 22, fecha: "2027-01-31", local: "Real Jaén CF", visitante: "AD Alcorcón" },
  { jornada: 22, fecha: "2027-01-31", local: "Gimnàstic de Tarragona", visitante: "SD Huesca" },
  { jornada: 22, fecha: "2027-01-31", local: "Real Madrid Castilla", visitante: "UE Sant Andreu" },
  { jornada: 22, fecha: "2027-01-31", local: "CD Teruel", visitante: "CF Rayo Majadahonda" },
  { jornada: 22, fecha: "2027-01-31", local: "Real Zaragoza", visitante: "Juventud de Torremolinos CF" },
  { jornada: 23, fecha: "2027-02-07", local: "AD Alcorcón", visitante: "Antequera CF" },
  { jornada: 23, fecha: "2027-02-07", local: "Algeciras CF", visitante: "CE Europa" },
  { jornada: 23, fecha: "2027-02-07", local: "FC Cartagena", visitante: "Real Zaragoza" },
  { jornada: 23, fecha: "2027-02-07", local: "Hércules de Alicante CF", visitante: "Águilas FC" },
  { jornada: 23, fecha: "2027-02-07", local: "UD Ibiza", visitante: "CD Teruel" },
  { jornada: 23, fecha: "2027-02-07", local: "Juventud de Torremolinos CF", visitante: "Atlético Madrileño" },
  { jornada: 23, fecha: "2027-02-07", local: "CF Rayo Majadahonda", visitante: "Real Jaén CF" },
  { jornada: 23, fecha: "2027-02-07", local: "Real Murcia CF", visitante: "Real Madrid Castilla" },
  { jornada: 23, fecha: "2027-02-07", local: "UE Sant Andreu", visitante: "Gimnàstic de Tarragona" },
  { jornada: 23, fecha: "2027-02-07", local: "Villarreal CF \"B\"", visitante: "SD Huesca" },
  { jornada: 24, fecha: "2027-02-14", local: "AD Alcorcón", visitante: "Atlético Madrileño" },
  { jornada: 24, fecha: "2027-02-14", local: "Antequera CF", visitante: "Hércules de Alicante CF" },
  { jornada: 24, fecha: "2027-02-14", local: "CE Europa", visitante: "Águilas FC" },
  { jornada: 24, fecha: "2027-02-14", local: "SD Huesca", visitante: "Algeciras CF" },
  { jornada: 24, fecha: "2027-02-14", local: "Real Jaén CF", visitante: "FC Cartagena" },
  { jornada: 24, fecha: "2027-02-14", local: "Real Murcia CF", visitante: "Juventud de Torremolinos CF" },
  { jornada: 24, fecha: "2027-02-14", local: "Gimnàstic de Tarragona", visitante: "Villarreal CF \"B\"" },
  { jornada: 24, fecha: "2027-02-14", local: "Real Madrid Castilla", visitante: "CF Rayo Majadahonda" },
  { jornada: 24, fecha: "2027-02-14", local: "CD Teruel", visitante: "UE Sant Andreu" },
  { jornada: 24, fecha: "2027-02-14", local: "Real Zaragoza", visitante: "UD Ibiza" },
  { jornada: 25, fecha: "2027-02-21", local: "Águilas FC", visitante: "Real Jaén CF" },
  { jornada: 25, fecha: "2027-02-21", local: "Algeciras CF", visitante: "Real Murcia CF" },
  { jornada: 25, fecha: "2027-02-21", local: "Atlético Madrileño", visitante: "Gimnàstic de Tarragona" },
  { jornada: 25, fecha: "2027-02-21", local: "FC Cartagena", visitante: "Real Madrid Castilla" },
  { jornada: 25, fecha: "2027-02-21", local: "Hércules de Alicante CF", visitante: "CD Teruel" },
  { jornada: 25, fecha: "2027-02-21", local: "UD Ibiza", visitante: "Villarreal CF \"B\"" },
  { jornada: 25, fecha: "2027-02-21", local: "Juventud de Torremolinos CF", visitante: "AD Alcorcón" },
  { jornada: 25, fecha: "2027-02-21", local: "CF Rayo Majadahonda", visitante: "Antequera CF" },
  { jornada: 25, fecha: "2027-02-21", local: "UE Sant Andreu", visitante: "SD Huesca" },
  { jornada: 25, fecha: "2027-02-21", local: "Real Zaragoza", visitante: "CE Europa" },
  { jornada: 26, fecha: "2027-02-28", local: "AD Alcorcón", visitante: "UE Sant Andreu" },
  { jornada: 26, fecha: "2027-02-28", local: "Antequera CF", visitante: "Algeciras CF" },
  { jornada: 26, fecha: "2027-02-28", local: "CE Europa", visitante: "Juventud de Torremolinos CF" },
  { jornada: 26, fecha: "2027-02-28", local: "SD Huesca", visitante: "CF Rayo Majadahonda" },
  { jornada: 26, fecha: "2027-02-28", local: "Real Jaén CF", visitante: "Atlético Madrileño" },
  { jornada: 26, fecha: "2027-02-28", local: "Real Murcia CF", visitante: "FC Cartagena" },
  { jornada: 26, fecha: "2027-02-28", local: "Gimnàstic de Tarragona", visitante: "Águilas FC" },
  { jornada: 26, fecha: "2027-02-28", local: "Real Madrid Castilla", visitante: "UD Ibiza" },
  { jornada: 26, fecha: "2027-02-28", local: "CD Teruel", visitante: "Real Zaragoza" },
  { jornada: 26, fecha: "2027-02-28", local: "Villarreal CF \"B\"", visitante: "Hércules de Alicante CF" },
  { jornada: 27, fecha: "2027-03-07", local: "Águilas FC", visitante: "Antequera CF" },
  { jornada: 27, fecha: "2027-03-07", local: "Algeciras CF", visitante: "Real Jaén CF" },
  { jornada: 27, fecha: "2027-03-07", local: "Atlético Madrileño", visitante: "CE Europa" },
  { jornada: 27, fecha: "2027-03-07", local: "FC Cartagena", visitante: "CD Teruel" },
  { jornada: 27, fecha: "2027-03-07", local: "Hércules de Alicante CF", visitante: "Gimnàstic de Tarragona" },
  { jornada: 27, fecha: "2027-03-07", local: "UD Ibiza", visitante: "SD Huesca" },
  { jornada: 27, fecha: "2027-03-07", local: "Juventud de Torremolinos CF", visitante: "Villarreal CF \"B\"" },
  { jornada: 27, fecha: "2027-03-07", local: "CF Rayo Majadahonda", visitante: "AD Alcorcón" },
  { jornada: 27, fecha: "2027-03-07", local: "UE Sant Andreu", visitante: "Real Murcia CF" },
  { jornada: 27, fecha: "2027-03-07", local: "Real Zaragoza", visitante: "Real Madrid Castilla" },
  { jornada: 28, fecha: "2027-03-14", local: "AD Alcorcón", visitante: "Hércules de Alicante CF" },
  { jornada: 28, fecha: "2027-03-14", local: "Algeciras CF", visitante: "Atlético Madrileño" },
  { jornada: 28, fecha: "2027-03-14", local: "Antequera CF", visitante: "Real Zaragoza" },
  { jornada: 28, fecha: "2027-03-14", local: "CE Europa", visitante: "FC Cartagena" },
  { jornada: 28, fecha: "2027-03-14", local: "SD Huesca", visitante: "Águilas FC" },
  { jornada: 28, fecha: "2027-03-14", local: "Real Jaén CF", visitante: "UE Sant Andreu" },
  { jornada: 28, fecha: "2027-03-14", local: "Real Murcia CF", visitante: "UD Ibiza" },
  { jornada: 28, fecha: "2027-03-14", local: "Gimnàstic de Tarragona", visitante: "Juventud de Torremolinos CF" },
  { jornada: 28, fecha: "2027-03-14", local: "Real Madrid Castilla", visitante: "CD Teruel" },
  { jornada: 28, fecha: "2027-03-14", local: "Villarreal CF \"B\"", visitante: "CF Rayo Majadahonda" },
  { jornada: 29, fecha: "2027-03-21", local: "Águilas FC", visitante: "Real Murcia CF" },
  { jornada: 29, fecha: "2027-03-21", local: "Atlético Madrileño", visitante: "Real Madrid Castilla" },
  { jornada: 29, fecha: "2027-03-21", local: "FC Cartagena", visitante: "Villarreal CF \"B\"" },
  { jornada: 29, fecha: "2027-03-21", local: "Hércules de Alicante CF", visitante: "SD Huesca" },
  { jornada: 29, fecha: "2027-03-21", local: "UD Ibiza", visitante: "Real Jaén CF" },
  { jornada: 29, fecha: "2027-03-21", local: "Juventud de Torremolinos CF", visitante: "Antequera CF" },
  { jornada: 29, fecha: "2027-03-21", local: "CF Rayo Majadahonda", visitante: "Algeciras CF" },
  { jornada: 29, fecha: "2027-03-21", local: "CD Teruel", visitante: "Gimnàstic de Tarragona" },
  { jornada: 29, fecha: "2027-03-21", local: "UE Sant Andreu", visitante: "CE Europa" },
  { jornada: 29, fecha: "2027-03-21", local: "Real Zaragoza", visitante: "AD Alcorcón" },
  { jornada: 30, fecha: "2027-03-28", local: "AD Alcorcón", visitante: "Real Madrid Castilla" },
  { jornada: 30, fecha: "2027-03-28", local: "Algeciras CF", visitante: "Juventud de Torremolinos CF" },
  { jornada: 30, fecha: "2027-03-28", local: "Antequera CF", visitante: "UE Sant Andreu" },
  { jornada: 30, fecha: "2027-03-28", local: "CE Europa", visitante: "UD Ibiza" },
  { jornada: 30, fecha: "2027-03-28", local: "SD Huesca", visitante: "Real Zaragoza" },
  { jornada: 30, fecha: "2027-03-28", local: "Real Jaén CF", visitante: "CD Teruel" },
  { jornada: 30, fecha: "2027-03-28", local: "CF Rayo Majadahonda", visitante: "Atlético Madrileño" },
  { jornada: 30, fecha: "2027-03-28", local: "Real Murcia CF", visitante: "Hércules de Alicante CF" },
  { jornada: 30, fecha: "2027-03-28", local: "Gimnàstic de Tarragona", visitante: "FC Cartagena" },
  { jornada: 30, fecha: "2027-03-28", local: "Villarreal CF \"B\"", visitante: "Águilas FC" },
  { jornada: 31, fecha: "2027-04-04", local: "Águilas FC", visitante: "CF Rayo Majadahonda" },
  { jornada: 31, fecha: "2027-04-04", local: "Atlético Madrileño", visitante: "UE Sant Andreu" },
  { jornada: 31, fecha: "2027-04-04", local: "FC Cartagena", visitante: "Antequera CF" },
  { jornada: 31, fecha: "2027-04-04", local: "CE Europa", visitante: "SD Huesca" },
  { jornada: 31, fecha: "2027-04-04", local: "Hércules de Alicante CF", visitante: "Algeciras CF" },
  { jornada: 31, fecha: "2027-04-04", local: "UD Ibiza", visitante: "AD Alcorcón" },
  { jornada: 31, fecha: "2027-04-04", local: "Juventud de Torremolinos CF", visitante: "Real Jaén CF" },
  { jornada: 31, fecha: "2027-04-04", local: "Real Madrid Castilla", visitante: "Villarreal CF \"B\"" },
  { jornada: 31, fecha: "2027-04-04", local: "CD Teruel", visitante: "Real Murcia CF" },
  { jornada: 31, fecha: "2027-04-04", local: "Real Zaragoza", visitante: "Gimnàstic de Tarragona" },
  { jornada: 32, fecha: "2027-04-11", local: "AD Alcorcón", visitante: "Real Murcia CF" },
  { jornada: 32, fecha: "2027-04-11", local: "Águilas FC", visitante: "FC Cartagena" },
  { jornada: 32, fecha: "2027-04-11", local: "Algeciras CF", visitante: "UD Ibiza" },
  { jornada: 32, fecha: "2027-04-11", local: "Antequera CF", visitante: "CD Teruel" },
  { jornada: 32, fecha: "2027-04-11", local: "SD Huesca", visitante: "Juventud de Torremolinos CF" },
  { jornada: 32, fecha: "2027-04-11", local: "Real Jaén CF", visitante: "Real Madrid Castilla" },
  { jornada: 32, fecha: "2027-04-11", local: "CF Rayo Majadahonda", visitante: "Hércules de Alicante CF" },
  { jornada: 32, fecha: "2027-04-11", local: "Gimnàstic de Tarragona", visitante: "CE Europa" },
  { jornada: 32, fecha: "2027-04-11", local: "UE Sant Andreu", visitante: "Real Zaragoza" },
  { jornada: 32, fecha: "2027-04-11", local: "Villarreal CF \"B\"", visitante: "Atlético Madrileño" },
  { jornada: 33, fecha: "2027-04-18", local: "Atlético Madrileño", visitante: "Águilas FC" },
  { jornada: 33, fecha: "2027-04-18", local: "FC Cartagena", visitante: "AD Alcorcón" },
  { jornada: 33, fecha: "2027-04-18", local: "Juventud de Torremolinos CF", visitante: "CF Rayo Majadahonda" },
  { jornada: 33, fecha: "2027-04-18", local: "Real Murcia CF", visitante: "Antequera CF" },
  { jornada: 33, fecha: "2027-04-18", local: "Gimnàstic de Tarragona", visitante: "UD Ibiza" },
  { jornada: 33, fecha: "2027-04-18", local: "Real Madrid Castilla", visitante: "SD Huesca" },
  { jornada: 33, fecha: "2027-04-18", local: "CD Teruel", visitante: "Algeciras CF" },
  { jornada: 33, fecha: "2027-04-18", local: "UE Sant Andreu", visitante: "Hércules de Alicante CF" },
  { jornada: 33, fecha: "2027-04-18", local: "Villarreal CF \"B\"", visitante: "CE Europa" },
  { jornada: 33, fecha: "2027-04-18", local: "Real Zaragoza", visitante: "Real Jaén CF" },
  { jornada: 34, fecha: "2027-04-25", local: "Águilas FC", visitante: "Real Zaragoza" },
  { jornada: 34, fecha: "2027-04-25", local: "Algeciras CF", visitante: "Villarreal CF \"B\"" },
  { jornada: 34, fecha: "2027-04-25", local: "Atlético Madrileño", visitante: "FC Cartagena" },
  { jornada: 34, fecha: "2027-04-25", local: "CE Europa", visitante: "AD Alcorcón" },
  { jornada: 34, fecha: "2027-04-25", local: "Hércules de Alicante CF", visitante: "Real Madrid Castilla" },
  { jornada: 34, fecha: "2027-04-25", local: "SD Huesca", visitante: "CD Teruel" },
  { jornada: 34, fecha: "2027-04-25", local: "UD Ibiza", visitante: "Antequera CF" },
  { jornada: 34, fecha: "2027-04-25", local: "Real Jaén CF", visitante: "Real Murcia CF" },
  { jornada: 34, fecha: "2027-04-25", local: "Juventud de Torremolinos CF", visitante: "UE Sant Andreu" },
  { jornada: 34, fecha: "2027-04-25", local: "CF Rayo Majadahonda", visitante: "Gimnàstic de Tarragona" },
  { jornada: 35, fecha: "2027-05-02", local: "AD Alcorcón", visitante: "Águilas FC" },
  { jornada: 35, fecha: "2027-05-02", local: "Antequera CF", visitante: "SD Huesca" },
  { jornada: 35, fecha: "2027-05-02", local: "FC Cartagena", visitante: "Algeciras CF" },
  { jornada: 35, fecha: "2027-05-02", local: "UD Ibiza", visitante: "Juventud de Torremolinos CF" },
  { jornada: 35, fecha: "2027-05-02", local: "Real Jaén CF", visitante: "Hércules de Alicante CF" },
  { jornada: 35, fecha: "2027-05-02", local: "Real Murcia CF", visitante: "CF Rayo Majadahonda" },
  { jornada: 35, fecha: "2027-05-02", local: "Real Madrid Castilla", visitante: "Gimnàstic de Tarragona" },
  { jornada: 35, fecha: "2027-05-02", local: "CD Teruel", visitante: "CE Europa" },
  { jornada: 35, fecha: "2027-05-02", local: "UE Sant Andreu", visitante: "Villarreal CF \"B\"" },
  { jornada: 35, fecha: "2027-05-02", local: "Real Zaragoza", visitante: "Atlético Madrileño" },
  { jornada: 36, fecha: "2027-05-09", local: "Águilas FC", visitante: "CD Teruel" },
  { jornada: 36, fecha: "2027-05-09", local: "Algeciras CF", visitante: "UE Sant Andreu" },
  { jornada: 36, fecha: "2027-05-09", local: "Atlético Madrileño", visitante: "UD Ibiza" },
  { jornada: 36, fecha: "2027-05-09", local: "CE Europa", visitante: "Antequera CF" },
  { jornada: 36, fecha: "2027-05-09", local: "Hércules de Alicante CF", visitante: "FC Cartagena" },
  { jornada: 36, fecha: "2027-05-09", local: "SD Huesca", visitante: "AD Alcorcón" },
  { jornada: 36, fecha: "2027-05-09", local: "Juventud de Torremolinos CF", visitante: "Real Madrid Castilla" },
  { jornada: 36, fecha: "2027-05-09", local: "CF Rayo Majadahonda", visitante: "Real Zaragoza" },
  { jornada: 36, fecha: "2027-05-09", local: "Gimnàstic de Tarragona", visitante: "Real Jaén CF" },
  { jornada: 36, fecha: "2027-05-09", local: "Villarreal CF \"B\"", visitante: "Real Murcia CF" },
  { jornada: 37, fecha: "2027-05-16", local: "AD Alcorcón", visitante: "Villarreal CF \"B\"" },
  { jornada: 37, fecha: "2027-05-16", local: "Antequera CF", visitante: "Gimnàstic de Tarragona" },
  { jornada: 37, fecha: "2027-05-16", local: "FC Cartagena", visitante: "Juventud de Torremolinos CF" },
  { jornada: 37, fecha: "2027-05-16", local: "UD Ibiza", visitante: "Hércules de Alicante CF" },
  { jornada: 37, fecha: "2027-05-16", local: "Real Jaén CF", visitante: "CE Europa" },
  { jornada: 37, fecha: "2027-05-16", local: "Real Murcia CF", visitante: "SD Huesca" },
  { jornada: 37, fecha: "2027-05-16", local: "Real Madrid Castilla", visitante: "Águilas FC" },
  { jornada: 37, fecha: "2027-05-16", local: "CD Teruel", visitante: "Atlético Madrileño" },
  { jornada: 37, fecha: "2027-05-16", local: "UE Sant Andreu", visitante: "CF Rayo Majadahonda" },
  { jornada: 37, fecha: "2027-05-16", local: "Real Zaragoza", visitante: "Algeciras CF" },
  { jornada: 38, fecha: "2027-05-23", local: "Águilas FC", visitante: "UE Sant Andreu" },
  { jornada: 38, fecha: "2027-05-23", local: "Algeciras CF", visitante: "AD Alcorcón" },
  { jornada: 38, fecha: "2027-05-23", local: "Atlético Madrileño", visitante: "Antequera CF" },
  { jornada: 38, fecha: "2027-05-23", local: "CE Europa", visitante: "Real Madrid Castilla" },
  { jornada: 38, fecha: "2027-05-23", local: "Hércules de Alicante CF", visitante: "Real Zaragoza" },
  { jornada: 38, fecha: "2027-05-23", local: "SD Huesca", visitante: "FC Cartagena" },
  { jornada: 38, fecha: "2027-05-23", local: "Juventud de Torremolinos CF", visitante: "CD Teruel" },
  { jornada: 38, fecha: "2027-05-23", local: "CF Rayo Majadahonda", visitante: "UD Ibiza" },
  { jornada: 38, fecha: "2027-05-23", local: "Gimnàstic de Tarragona", visitante: "Real Murcia CF" },
  { jornada: 38, fecha: "2027-05-23", local: "Villarreal CF \"B\"", visitante: "Real Jaén CF" },
];

/** Los veinte equipos del grupo, como los escribe la federación. */
export const EQUIPOS = [
  "AD Alcorcón",
  "Algeciras CF",
  "Antequera CF",
  "Atlético Madrileño",
  "CD Teruel",
  "CE Europa",
  "CF Rayo Majadahonda",
  "FC Cartagena",
  "Gimnàstic de Tarragona",
  "Hércules de Alicante CF",
  "Juventud de Torremolinos CF",
  "Real Jaén CF",
  "Real Madrid Castilla",
  "Real Murcia CF",
  "Real Zaragoza",
  "SD Huesca",
  "UD Ibiza",
  "UE Sant Andreu",
  "Villarreal CF \"B\"",
  "Águilas FC"
] as const;
