[{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useMemo'.",
	"source": "ts",
	"startLineNumber": 3,
	"startColumn": 12,
	"endLineNumber": 3,
	"endColumn": 19,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useState'.",
	"source": "ts",
	"startLineNumber": 3,
	"startColumn": 21,
	"endLineNumber": 3,
	"endColumn": 29,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'ABPRow'.",
	"source": "ts",
	"startLineNumber": 5,
	"startColumn": 15,
	"endLineNumber": 5,
	"endColumn": 21,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2451",
	"severity": 8,
	"message": "Cannot redeclare block-scoped variable 'Z_Y'.",
	"source": "ts",
	"startLineNumber": 39,
	"startColumn": 9,
	"endLineNumber": 39,
	"endColumn": 12,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 48,
	"startColumn": 10,
	"endLineNumber": 48,
	"endColumn": 25,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 202,
	"startColumn": 12,
	"endLineNumber": 202,
	"endColumn": 31,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2451",
	"severity": 8,
	"message": "Cannot redeclare block-scoped variable 'remateCoords'.",
	"source": "ts",
	"startLineNumber": 207,
	"startColumn": 9,
	"endLineNumber": 207,
	"endColumn": 21,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 219,
	"startColumn": 12,
	"endLineNumber": 219,
	"endColumn": 31,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2323",
	"severity": 8,
	"message": "Cannot redeclare exported variable 'default'.",
	"source": "ts",
	"startLineNumber": 238,
	"startColumn": 27,
	"endLineNumber": 238,
	"endColumn": 39,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 238,
	"startColumn": 27,
	"endLineNumber": 238,
	"endColumn": 39,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useMemo'.",
	"source": "ts",
	"startLineNumber": 820,
	"startColumn": 14,
	"endLineNumber": 820,
	"endColumn": 21,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useState'.",
	"source": "ts",
	"startLineNumber": 820,
	"startColumn": 23,
	"endLineNumber": 820,
	"endColumn": 31,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'ABPRow'.",
	"source": "ts",
	"startLineNumber": 822,
	"startColumn": 17,
	"endLineNumber": 822,
	"endColumn": 23,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2451",
	"severity": 8,
	"message": "Cannot redeclare block-scoped variable 'Z_Y'.",
	"source": "ts",
	"startLineNumber": 856,
	"startColumn": 11,
	"endLineNumber": 856,
	"endColumn": 14,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 865,
	"startColumn": 12,
	"endLineNumber": 865,
	"endColumn": 27,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 1019,
	"startColumn": 14,
	"endLineNumber": 1019,
	"endColumn": 33,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2451",
	"severity": 8,
	"message": "Cannot redeclare block-scoped variable 'remateCoords'.",
	"source": "ts",
	"startLineNumber": 1024,
	"startColumn": 11,
	"endLineNumber": 1024,
	"endColumn": 23,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 1036,
	"startColumn": 14,
	"endLineNumber": 1036,
	"endColumn": 33,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2323",
	"severity": 8,
	"message": "Cannot redeclare exported variable 'default'.",
	"source": "ts",
	"startLineNumber": 1055,
	"startColumn": 29,
	"endLineNumber": 1055,
	"endColumn": 41,
	"modelVersionId": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Usuario/Downloads/RMCF/Real-Madrid-Castilla-26-27/app/setpieces_def/components/ABPFlowField.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 1055,
	"startColumn": 29,
	"endLineNumber": 1055,
	"endColumn": 41,
	"modelVersionId": 48,
	"origin": "extHost1"
}]