/**
 * Robos y transiciones etiquetados a mano sobre el vídeo.
 *
 * ESTE FICHERO SE GENERA. No lo edites: lo escribe
 * scripts/transiciones-datos.mjs a partir de los CSV de
 * Downloads/RMCF CASTILLA/ANALISIS TRANSICIONES.
 *
 * Generado: 2026-10-04
 */

export type Accion = "ADELANTE" | "HORIZONTAL_ATRAS" | "DESPEJE" | "PERDIDA";
export type Confianza = "alta" | "media" | "baja";

export type Robo = {
  /** Segundo del vídeo en que el balón pasa a ser nuestro. */
  seg: number;
  zona: string;
  carril: string;
  accion: Accion;
  /** Cómo acaba la posesión que nace del robo. Vacío en los bloques viejos. */
  desenlace: string;
  duracion: number | null;
  pases: string;
  detalle: string;
  confianza: Confianza;
  bloque: string;
};

export type Gol = { seg: number; de: "castilla" | "rival"; texto: string };

export type PartidoTransiciones = {
  id: string;
  jornada: string;
  rival: string;
  local: boolean;
  fecha: string;
  resultado: string;
  /** Dónde está el vídeo, para poder volver a él y para el panel de actualizar. */
  video: string;
  segundosVideo: number;
  bloquesTotales: number;
  bloquesCerrados: number;
  /** Segundos de vídeo mirados de verdad, contando los bloques a medias. */
  segundosRevisados: number;
  notas: string[];
  goles: Gol[];
  robos: Robo[];
};

export const PARTIDOS: PartidoTransiciones[] = [
  {
    "id": "torremolinos",
    "jornada": "J2",
    "rival": "Juventud Torremolinos",
    "local": true,
    "fecha": "2026-09-05",
    "resultado": "",
    "video": "",
    "segundosVideo": 6060,
    "bloquesTotales": 20,
    "notas": [
      "El vídeo arranca en el saque inicial y su reloj va casi a la par del reloj del partido.",
      "El juego se detiene en el 28'31\" por una lesión y ya no se reanuda: enlaza con la pausa de hidratación, campo vacío y aspersores, hasta el 31'30\".",
      "El Castilla ataca hacia arriba de la imagen en las dos partes.",
      "La 1ª parte acaba en el minuto 50:31 del vídeo (45+6, con el marcador 1-0) y el descanso está cortado: el vídeo salta en el 50:38 y la 2ª parte arranca en el 50:41. A partir de ahí el minuto del vídeo va unos 5:40 por delante del reloj del partido."
    ],
    "goles": [
      {
        "seg": 1555,
        "de": "castilla",
        "texto": "Gol del Castilla, concedido tras una revisión de la jugada"
      },
      {
        "seg": 5343,
        "de": "castilla",
        "texto": "Gol del Castilla, nacido del robo del 88'53\""
      }
    ],
    "bloquesCerrados": 20,
    "segundosRevisados": 6060,
    "robos": [
      {
        "seg": 24,
        "zona": "campo propio",
        "carril": "",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "",
        "duracion": null,
        "pases": "",
        "detalle": "duelo en banda izquierda propia: le quita el balon al rival y conduce en diagonal hacia la banda",
        "confianza": "media",
        "bloque": "b00000"
      },
      {
        "seg": 83,
        "zona": "medio campo",
        "carril": "",
        "accion": "DESPEJE",
        "desenlace": "",
        "duracion": null,
        "pases": "",
        "detalle": "entrada a ras de suelo cerca del circulo central: saca el balon lejos y sale por la banda",
        "confianza": "baja",
        "bloque": "b00000"
      },
      {
        "seg": 114,
        "zona": "medio campo",
        "carril": "",
        "accion": "ADELANTE",
        "desenlace": "",
        "duracion": null,
        "pases": "",
        "detalle": "roba en el duelo junto a la linea de medio campo y conduce hacia arriba entrando en campo rival",
        "confianza": "alta",
        "bloque": "b00000"
      },
      {
        "seg": 211,
        "zona": "campo propio",
        "carril": "",
        "accion": "ADELANTE",
        "desenlace": "",
        "duracion": null,
        "pases": "",
        "detalle": "corta un pase corto del rival y dos segundos despues el balon avanza en diagonal",
        "confianza": "media",
        "bloque": "b00000"
      },
      {
        "seg": 263,
        "zona": "campo rival",
        "carril": "",
        "accion": "ADELANTE",
        "desenlace": "",
        "duracion": null,
        "pases": "",
        "detalle": "presion alta sobre el lateral rival en su ultimo tercio: le gana el balon y conduce hasta el vertice del area",
        "confianza": "media",
        "bloque": "b00000"
      },
      {
        "seg": 431,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 12,
        "pases": "4",
        "detalle": "presiona al conductor rival junto a la linea de medio campo por la izquierda, le gana el balon y conduce hacia arriba, la jugada progresa hasta meter el balon en el area rival donde se queda el portero",
        "confianza": "media",
        "bloque": "b00300"
      },
      {
        "seg": 480,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 5,
        "pases": "1",
        "detalle": "balon suelto en la salida corta del rival con un jugador del Castilla encima, lo gana el Castilla en la banda izquierda del campo rival pero el balon va hacia la linea y el rival lo recupera enseguida",
        "confianza": "baja",
        "bloque": "b00300"
      },
      {
        "seg": 995,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 11,
        "pases": "4",
        "detalle": "duelo en la banda izquierda junto al circulo central, el rival pierde el control y un jugador del Castilla sale conduciendo, la jugada muere con el balon dentro del area rival y el portero achicando a los pies",
        "confianza": "media",
        "bloque": "b00900"
      },
      {
        "seg": 1386,
        "zona": "campo propio",
        "carril": "",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "",
        "duracion": null,
        "pases": "",
        "detalle": "banda derecha, cerca del area propia: un jugador del Torremolinos conduce por la linea y nuestro lateral le aguanta el duelo, el balon se escapa del jugador del Torremolinos y nuestro jugador llega antes — conduce hacia dentro y la cede al portero naranja, que la recoge en el area",
        "confianza": "media",
        "bloque": "b01200"
      },
      {
        "seg": 1645,
        "zona": "campo rival",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "REMATE",
        "duracion": 2,
        "pases": "0",
        "detalle": "presion encima del central en la frontal del area, le quita el balon y encara, el portero verde sale a los pies y bloca el remate dentro del area pequena",
        "confianza": "media",
        "bloque": "b01500"
      },
      {
        "seg": 1665,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "FUERA",
        "duracion": 6,
        "pases": "?",
        "detalle": "el Torremolinos saca el balon desde su area por su banda izquierda y nuestro jugador se lo roba en carrera junto a la linea, siguen duelos en la banda y el balon acaba saliendo por el lateral",
        "confianza": "media",
        "bloque": "b01500"
      },
      {
        "seg": 2092,
        "zona": "medio campo",
        "carril": "",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "",
        "duracion": null,
        "pases": "",
        "detalle": "disputa en la banda derecha junto a la linea de medio campo: el balon esta en un jugador del Torremolinos (2088), dos jugadores del Castilla le entran al suelo (2090-2091) y el balon queda para el Castilla, que lo saca hacia dentro y hacia atras",
        "confianza": "baja",
        "bloque": "b01800"
      },
      {
        "seg": 2232,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 7,
        "pases": "1",
        "detalle": "dos jugadores del Castilla aprietan al jugador del Torremolinos que conducia por su banda derecha pasado el medio campo y el balon queda para el Castilla, que conduce en diagonal hacia dentro y mete el balon en el area rival, donde lo saca un defensa",
        "confianza": "media",
        "bloque": "b02100"
      },
      {
        "seg": 2473,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 2,
        "pases": "0",
        "detalle": "un jugador del Castilla entra encima del conductor del Torremolinos dentro del circulo central y le quita el balon, lo lleva dos segundos y el Torremolinos se lo vuelve a quitar antes de que salga un pase",
        "confianza": "media",
        "bloque": "b02400"
      },
      {
        "seg": 2502,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "DESPEJE",
        "desenlace": "FUERA",
        "duracion": 2,
        "pases": "0",
        "detalle": "nuestro central 5 gana la carrera al extremo del Torremolinos pegado a la banda derecha y le roba el balon, pero lo empuja hacia la linea y el balon se marcha fuera",
        "confianza": "baja",
        "bloque": "b02400"
      },
      {
        "seg": 2864,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 15,
        "pases": "3",
        "detalle": "duelo en la banda derecha junto al banquillo rival con el jugador del Torremolinos conduciendo y un jugador del Castilla encima: en 2863 el balon queda suelto y en 2865 ya lo controla el Castilla, que sale conduciendo hacia arriba por el centro-derecha, progresa hasta el borde del area rival y alli un defensa del Torremolinos se lo vuelve a quitar justo antes de que el juego se detenga",
        "confianza": "media",
        "bloque": "b02700"
      },
      {
        "seg": 3221,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "FALTA_CONTRA",
        "duracion": 7,
        "pases": "?",
        "detalle": "presion alta sobre la salida corta del rival tras su saque de puerta: en 3219 un jugador del Castilla entra al jugador del Torremolinos que conduce por nuestra derecha y en 3221-3222 el balon ya lo lleva un jugador del Castilla junto al area rival — lo saca hacia dentro, sigue el barullo en la frontal y en 3227-3228 el arbitro para con un jugador del Torremolinos en el suelo",
        "confianza": "media",
        "bloque": "b03000"
      },
      {
        "seg": 3272,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "FUERA",
        "duracion": 2,
        "pases": "?",
        "detalle": "disputa con entrada a ras de suelo en la banda izquierda dentro del campo rival: en 3270 el balon queda suelto, en 3271 caen juntos un jugador de cada equipo y en 3272 el balon esta a los pies de un jugador del Castilla, que lo saca hacia atras y el juego se detiene enseguida (saque de banda y cambio del rival)",
        "confianza": "baja",
        "bloque": "b03000"
      },
      {
        "seg": 3371,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "1",
        "detalle": "presion sobre el rival que conducia por nuestra derecha pasada la linea de medio campo: se lo quita y lo juega en largo hacia el area, pero el central rival corta el envio junto a su area",
        "confianza": "alta",
        "bloque": "b03300"
      },
      {
        "seg": 3433,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "FALTA_FAVOR",
        "duracion": 5,
        "pases": "2",
        "detalle": "interceptacion junto a la banda derecha en campo rival: el rival saca el balon hacia la linea y un jugador del Castilla se lo quita y lo mete hacia dentro, acaba en barullo y el arbitro pita falta con un jugador nuestro en el suelo",
        "confianza": "media",
        "bloque": "b03300"
      },
      {
        "seg": 3603,
        "zona": "campo rival",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 2,
        "pases": "0",
        "detalle": "presion encima del conductor rival entre el circulo central y la frontal, le quita el balon y lo empuja en diagonal a la derecha pero un jugador del Torremolinos llega antes y lo recupera",
        "confianza": "media",
        "bloque": "b03600"
      },
      {
        "seg": 3607,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 2,
        "pases": "1",
        "detalle": "el jugador del Torremolinos conduce hacia la banda derecha del ataque y nuestro jugador que le persigue le roba el balon, lo mete hacia dentro y el rival vuelve a quedarselo",
        "confianza": "media",
        "bloque": "b03600"
      },
      {
        "seg": 3614,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 5,
        "pases": "2",
        "detalle": "disputa junto al vertice izquierdo del area rival: se le va el balon al jugador del Torremolinos que conducia, un jugador del Castilla lo gana con un jugador del Torremolinos encima, se saca en diagonal a la derecha y el rival lo recupera en 3619",
        "confianza": "baja",
        "bloque": "b03600"
      },
      {
        "seg": 3743,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "1",
        "detalle": "un jugador del Castilla va encima del jugador del Torremolinos que conduce junto al circulo central y le quita el balon, se saca hacia delante pero el rival lo recupera enseguida",
        "confianza": "baja",
        "bloque": "b03600"
      },
      {
        "seg": 3903,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 5,
        "pases": "0",
        "detalle": "presion alta sobre el defensa rival junto a su area: le quita el balon y conduce solo hacia porteria, mete el balon en el area pero el portero verde le sale y lo ataja",
        "confianza": "alta",
        "bloque": "b03900"
      },
      {
        "seg": 4029,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "0",
        "detalle": "entrada de un jugador del Castilla sobre el conductor rival junto al circulo central: el balon queda suelto y un jugador del Castilla llega primero, pero el rival lo recupera al segundo siguiente",
        "confianza": "baja",
        "bloque": "b03900"
      },
      {
        "seg": 4278,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "REMATE",
        "duracion": 11,
        "pases": "3",
        "detalle": "entrada de un jugador del Castilla sobre el rival que conducia justo en la linea de medio campo por la derecha, el Castilla sale con el balon y progresa por la banda derecha, envio raso al area en 4287 y remate que el portero verde ataja en el suelo en 4289",
        "confianza": "media",
        "bloque": "b04200"
      },
      {
        "seg": 4568,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "FALTA_CONTRA",
        "duracion": 11,
        "pases": "2",
        "detalle": "balon suelto y disputado junto a la linea de medio campo por la izquierda, en 4566-4567 un jugador del Castilla y un jugador del Torremolinos forcejean encima del balon y en 4568 nuestro jugador sale conduciendo hacia arriba con el jugador del Torremolinos a la espalda, envio largo y un jugador del Castilla recoge por la derecha hasta el ultimo tercio, donde en 4579 hay un choque, el arbitro para y la falta la acaba sacando el Torremolinos",
        "confianza": "media",
        "bloque": "b04500"
      },
      {
        "seg": 4623,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 5,
        "pases": "1",
        "detalle": "presion alta sobre el defensa del Torremolinos junto a su propia area por la izquierda, en 4622 el jugador del Torremolinos lleva el balon con un jugador del Castilla encima y en 4623 nuestro jugador ya golpea el balon y lo saca hacia la banda, pero en el barullo de la linea de cal el Torremolinos lo vuelve a coger hacia 4628",
        "confianza": "baja",
        "bloque": "b04500"
      },
      {
        "seg": 4819,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "1",
        "detalle": "entrada de un companero sobre el rival justo pasada la linea de medio campo y el 21 recoge el rechace cerca del circulo central antes de tocarla en corto hacia la izquierda",
        "confianza": "media",
        "bloque": "b04800"
      },
      {
        "seg": 4826,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 4,
        "pases": "0",
        "detalle": "duelo ganado en la banda izquierda junto al medio campo y conduccion hacia arriba hasta la frontal del area rival donde nos la quitan",
        "confianza": "media",
        "bloque": "b04800"
      },
      {
        "seg": 4837,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "REMATE",
        "duracion": 53,
        "pases": "?",
        "detalle": "cortamos la salida de balon del Torremolinos por su izquierda y arranca una posesion muy larga que termina con balones sueltos y remates dentro de su area",
        "confianza": "media",
        "bloque": "b04800"
      },
      {
        "seg": 5033,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 13,
        "pases": "?",
        "detalle": "robo en el duelo sobre la linea de medio campo por el centro y progresion inmediata hasta la frontal del area rival donde muere la jugada",
        "confianza": "media",
        "bloque": "b04800"
      },
      {
        "seg": 5241,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 2,
        "pases": "0",
        "detalle": "en 5238-5240 el balon lo conduce un jugador del Torremolinos junto al circulo central, un jugador del Castilla le entra encima y en 5241 el balon ya es suyo, pero conduce hacia atras-derecha y en 5243 se lo vuelven a quitar en la banda derecha",
        "confianza": "media",
        "bloque": "b05100"
      },
      {
        "seg": 5300,
        "zona": "campo rival",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 6,
        "pases": "1",
        "detalle": "segunda jugada del saque de puerta: en 5299 el balon es de un jugador del Torremolinos con un jugador del Castilla pegado, en 5300 lo gana el Castilla, lo saca hacia delante por la izquierda y en 5305-5306 un jugador del Castilla llega a linea de fondo dentro del area, donde un central despeja a corner",
        "confianza": "media",
        "bloque": "b05100"
      },
      {
        "seg": 5333,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "REMATE",
        "duracion": 9,
        "pases": "?",
        "detalle": "presion de dos jugadores del Castilla sobre el lateral rival junto a la banda derecha (5331 el balon es del Torremolinos, 5332 lo aprietan, 5333 lo recupera el 21), el Castilla progresa por la derecha, cambia a la izquierda del area y en 5342 tira — el balon entra y es gol",
        "confianza": "alta",
        "bloque": "b05100"
      },
      {
        "seg": 5448,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "FUERA",
        "duracion": 5,
        "pases": "0",
        "detalle": "un jugador del Torremolinos conduce por la banda izquierda hacia el area del Castilla con un jugador del Castilla pegado a el, en 5443 nuestro jugador entra y el balon queda suelto, tras un barullo de varios segundos nuestro jugador sale con el balon pegado a la linea de cal en 5448 y lo protege bajo presion sin llegar a dar pase, en 5453 el balon sale por la banda y el asistente senala saque de banda para el Castilla",
        "confianza": "media",
        "bloque": "b05400"
      },
      {
        "seg": 5712,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "POSESION",
        "duracion": 16,
        "pases": "?",
        "detalle": "el 11 del Torremolinos conduce por nuestra banda izquierda y un jugador del Castilla le entra encima junto a la linea en 5710-5712: en 5713 el balon ya lo lleva el 10 del Castilla, que conduce hacia dentro mientras el rival protesta falta, y el equipo circula en campo propio y medio campo sin llegar al ultimo tercio",
        "confianza": "media",
        "bloque": "b05700"
      },
      {
        "seg": 5952,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "POSESION",
        "duracion": 16,
        "pases": "?",
        "detalle": "disputa sobre la linea de medio campo por la izquierda: en 5950 pelean el balon un jugador del Castilla y un jugador del Torremolinos, en 5951 lo lleva el jugador del Torremolinos con nuestro jugador encima y en 5952 queda suelto y llega antes el Castilla, que en 5954-5956 lo conduce hacia atras por la izquierda y lo hace circular por campo propio",
        "confianza": "media",
        "bloque": "b05700"
      }
    ]
  },
  {
    "id": "aguilas",
    "jornada": "J3",
    "rival": "Águilas FC",
    "local": false,
    "fecha": "2026-09-12",
    "resultado": "",
    "video": "",
    "segundosVideo": 6158,
    "bloquesTotales": 21,
    "notas": [
      "Revisado entero, pero con menos lupa que el J2. Los 40 robos son un suelo, no un total: el que empieza y acaba en un par de segundos no se ve.",
      "Y el sesgo no es sólo de cantidad: con menos lupa se ven sobre todo los robos que llevan a algo, y por eso aquí sale 90% hacia delante y en el J2 un 60%. NO compares ese porcentaje entre los dos partidos; para eso hace falta volver a mirar el J3 con el detalle del J2.",
      "Aquí la dirección SÍ cambia: el Castilla ataca hacia arriba de la imagen hasta el segundo 3016 y hacia abajo desde el 3017.",
      "El descanso no está grabado: hay un corte de montaje entre el 3016 y el 3017. No hay marcador en pantalla, así que los minutos son de vídeo.",
      "Pausa de hidratación del 83'09\" al 84'53\". El vídeo acaba en el 102'37\" con el partido todavía en juego.",
      "En el 74'10\" nuestro portero le para un penalti al Águilas."
    ],
    "goles": [
      {
        "seg": 687,
        "de": "rival",
        "texto": "Gol del Águilas, en una falta al borde del área"
      }
    ],
    "bloquesCerrados": 21,
    "segundosRevisados": 6158,
    "robos": [
      {
        "seg": 59,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "1",
        "detalle": "entrada en banda izquierda sobre el rival que conducia y pase largo al espacio que no encuentra a nadie",
        "confianza": "media",
        "bloque": "b00000"
      },
      {
        "seg": 204,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 8,
        "pases": "3",
        "detalle": "gana el segundo balon en el duelo aereo del centro tras el despeje del rival y el Castilla progresa por la banda derecha hasta el ultimo tercio",
        "confianza": "media",
        "bloque": "b00000"
      },
      {
        "seg": 343,
        "zona": "campo rival",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 20,
        "pases": "?",
        "detalle": "presion alta sobre la salida del Águilas junto al area y conduccion hacia la banda derecha antes de perderla cerca del medio campo",
        "confianza": "media",
        "bloque": "b00300"
      },
      {
        "seg": 430,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "POSESION",
        "duracion": 42,
        "pases": "?",
        "detalle": "roba en el centro y saca por la izquierda abriendo una fase larga de ataque en campo del Águilas",
        "confianza": "media",
        "bloque": "b00300"
      },
      {
        "seg": 466,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 10,
        "pases": "2",
        "detalle": "presion alta en campo del Águilas gana el balon en el duelo y sigue el ataque hasta perderlo",
        "confianza": "baja",
        "bloque": "b00300"
      },
      {
        "seg": 554,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "FALTA_FAVOR",
        "duracion": 15,
        "pases": "2",
        "detalle": "corta la subida del Águilas por esa banda conduce hacia el centro y acaba recibiendo falta",
        "confianza": "media",
        "bloque": "b00300"
      },
      {
        "seg": 997,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "FALTA_FAVOR",
        "duracion": 12,
        "pases": "2",
        "detalle": "el central 2 le quita el balon al extremo del Águilas en el borde del area propia y el 11 la saca en conduccion por la izquierda",
        "confianza": "media",
        "bloque": "b00900"
      },
      {
        "seg": 1091,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 9,
        "pases": "?",
        "detalle": "entrada por abajo de nuestro centrocampista al conductor del Águilas justo pasada la linea de medio campo y el balon queda suelto para el Castilla que sale por la izquierda",
        "confianza": "media",
        "bloque": "b00900"
      },
      {
        "seg": 1112,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "ATRAS_PORTERO",
        "duracion": 8,
        "pases": "3",
        "detalle": "el lateral 2 entra al extremo del Águilas pegado a la banda derecha el balon queda muerto y lo recoge el Castilla para salir hacia delante",
        "confianza": "media",
        "bloque": "b00900"
      },
      {
        "seg": 1201,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "POSESION",
        "duracion": 68,
        "pases": "?",
        "detalle": "disputa ganada en el medio campo y salimos jugando sin llegar al ultimo tercio",
        "confianza": "media",
        "bloque": "b01200"
      },
      {
        "seg": 1301,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "ATRAS_PORTERO",
        "duracion": 15,
        "pases": "3",
        "detalle": "entrada sobre el rival junto a nuestra frontal y sacamos por la izquierda",
        "confianza": "media",
        "bloque": "b01200"
      },
      {
        "seg": 1478,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "POSESION",
        "duracion": 21,
        "pases": "?",
        "detalle": "balon ganado en duelo en nuestro carril derecho y lo conservamos",
        "confianza": "baja",
        "bloque": "b01200"
      },
      {
        "seg": 1503,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 9,
        "pases": "2",
        "detalle": "interceptacion en la salida del rival y salimos por el centro",
        "confianza": "media",
        "bloque": "b01500"
      },
      {
        "seg": 1550,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 10,
        "pases": "2",
        "detalle": "balon ganado en presion alta por izquierda y cambiamos de carril",
        "confianza": "baja",
        "bloque": "b01500"
      },
      {
        "seg": 1565,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 11,
        "pases": "2",
        "detalle": "robo al borde de nuestra area tras el ataque rival por nuestra derecha",
        "confianza": "media",
        "bloque": "b01500"
      },
      {
        "seg": 1955,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "1",
        "detalle": "nuestro central se anticipa en la banda izquierda cerca del medio campo el rival cae al suelo y el saca un envio largo hacia delante que el Águilas corta",
        "confianza": "media",
        "bloque": "b01800"
      },
      {
        "seg": 2232,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "FALTA_FAVOR",
        "duracion": 7,
        "pases": "1",
        "detalle": "entrada de un jugador del Castilla sobre el conductor del Águilas en banda derecha y el rival derriba al recuperador",
        "confianza": "media",
        "bloque": "b02100"
      },
      {
        "seg": 2364,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 10,
        "pases": "2",
        "detalle": "presion alta en banda izquierda cerca del area rival y el Castilla se queda el balon para conducir",
        "confianza": "baja",
        "bloque": "b02100"
      },
      {
        "seg": 2390,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "POSESION",
        "duracion": 12,
        "pases": "?",
        "detalle": "disputa ganada cerca del circulo central y conduccion por el carril izquierdo",
        "confianza": "baja",
        "bloque": "b02100"
      },
      {
        "seg": 2463,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 7,
        "pases": "1",
        "detalle": "entrada y presion junto al area del Águilas el balon queda ante el portero que sale y el rival lo recupera",
        "confianza": "media",
        "bloque": "b02400"
      },
      {
        "seg": 2474,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "FALTA_FAVOR",
        "duracion": 8,
        "pases": "3",
        "detalle": "robo en la salida del Águilas por la izquierda y el Castilla progresa hasta que le hacen falta junto al circulo central",
        "confianza": "media",
        "bloque": "b02400"
      },
      {
        "seg": 2512,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 7,
        "pases": "2",
        "detalle": "robo en la presion junto al circulo central y conduccion directa hasta meter el balon en el area del Águilas donde lo bloca el portero",
        "confianza": "media",
        "bloque": "b02400"
      },
      {
        "seg": 2748,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "REMATE",
        "duracion": 20,
        "pases": "?",
        "detalle": "disputa ganada en la banda izquierda y contraataque que acaba en remate atajado por el portero rival",
        "confianza": "media",
        "bloque": "b02700"
      },
      {
        "seg": 2936,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "FUERA",
        "duracion": 5,
        "pases": "1",
        "detalle": "presion alta sobre la salida de balon del Águilas y el balon acaba fuera por linea de fondo",
        "confianza": "baja",
        "bloque": "b02700"
      },
      {
        "seg": 3183,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 13,
        "pases": "?",
        "detalle": "presion alta sobre la salida del Águilas balon suelto ganado y conduccion hasta el area que acaba en corner",
        "confianza": "media",
        "bloque": "b03000"
      },
      {
        "seg": 3580,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "DESPEJE",
        "desenlace": "PERDIDA",
        "duracion": 6,
        "pases": "1",
        "detalle": "duelo ganado en la banda de nuestra derecha y balonazo largo que atrapa el portero del Águilas",
        "confianza": "media",
        "bloque": "b03300"
      },
      {
        "seg": 3660,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 10,
        "pases": "2",
        "detalle": "presion alta en banda y el balon acaba en el area del Águilas con el portero rojo despejando",
        "confianza": "media",
        "bloque": "b03600"
      },
      {
        "seg": 3814,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 18,
        "pases": "3",
        "detalle": "recuperacion en el circulo central tras el saque del portero rival y salida hacia la banda",
        "confianza": "baja",
        "bloque": "b03600"
      },
      {
        "seg": 3877,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "FUERA",
        "duracion": 15,
        "pases": "2",
        "detalle": "varios jugadores del Castilla encima de la salida del Águilas y el balon se gana cerca del area grande",
        "confianza": "media",
        "bloque": "b03600"
      },
      {
        "seg": 4042,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 13,
        "pases": "1",
        "detalle": "balon ganado en el amontonamiento del centro y conduccion por la banda",
        "confianza": "baja",
        "bloque": "b03900"
      },
      {
        "seg": 4072,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "FALTA_FAVOR",
        "duracion": 16,
        "pases": "2",
        "detalle": "duelo ganado cerca del area del Águilas que termina en falta a favor junto al area",
        "confianza": "media",
        "bloque": "b03900"
      },
      {
        "seg": 4172,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 12,
        "pases": "2",
        "detalle": "balon suelto ganado en nuestro campo y salida conduciendo desde el circulo central",
        "confianza": "media",
        "bloque": "b03900"
      },
      {
        "seg": 4707,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 12,
        "pases": "2",
        "detalle": "balon disputado cerca del circulo ganado por un jugador del Castilla y abierto al carril izquierdo antes de volver a perderlo",
        "confianza": "media",
        "bloque": "b04500"
      },
      {
        "seg": 4815,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "FALTA_CONTRA",
        "duracion": 15,
        "pases": "2",
        "detalle": "el Castilla gana el balon dentro de su area tras la presion del Águilas y sale conduciendo por su izquierda hasta que el arbitro corta la jugada",
        "confianza": "baja",
        "bloque": "b04800"
      },
      {
        "seg": 5222,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 14,
        "pases": "2",
        "detalle": "balon dividido ganado por un jugador del Castilla junto al circulo central y conduccion hacia campo rival",
        "confianza": "media",
        "bloque": "b05100"
      },
      {
        "seg": 5308,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "FUERA",
        "duracion": 13,
        "pases": "?",
        "detalle": "recuperacion en el medio y ataque por la banda que acaba en la linea de fondo del Águilas",
        "confianza": "baja",
        "bloque": "b05100"
      },
      {
        "seg": 5666,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "REMATE",
        "duracion": 10,
        "pases": "?",
        "detalle": "balon dividido ganado por un jugador del Castilla cerca del medio campo y ataque que acaba en parada del portero del Águilas",
        "confianza": "media",
        "bloque": "b05400"
      },
      {
        "seg": 5714,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 6,
        "pases": "1",
        "detalle": "corta un pase del Águilas en la banda con un jugador del Castilla encima y el balon se vuelve a perder enseguida",
        "confianza": "baja",
        "bloque": "b05700"
      },
      {
        "seg": 5808,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 13,
        "pases": "2",
        "detalle": "recupera cerca del medio campo y conduce por su banda derecha hasta campo rival donde la pierde en un multiple junto a la linea",
        "confianza": "media",
        "bloque": "b05700"
      },
      {
        "seg": 6024,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 9,
        "pases": "1",
        "detalle": "interceptacion en el borde del circulo central de un balon que el 3 del Águilas saca presionado y conduccion larga por la banda izquierda hasta que el 6 del Águilas se la quita",
        "confianza": "media",
        "bloque": "b06000"
      }
    ]
  },
  {
    "id": "sant-andreu",
    "jornada": "J4",
    "rival": "UE Sant Andreu",
    "local": false,
    "fecha": "2026-09-21",
    "resultado": "1-1",
    "video": "C:/Users/Usuario/Downloads/SANT ANDREU - RM CASTILLA.mov",
    "segundosVideo": 5914,
    "bloquesTotales": 20,
    "notas": [
      "Sacado del timeline de Hudl (el etiquetado de Wyscout del partido), no mirando imagen a imagen: salen TODOS los robos del partido, también los cortos que a ojo se escapaban. Por eso hay más que en el J2 y el J3, y el reparto no se compara con ellos sin decirlo.",
      "Cuenta como robo la interceptación, el duelo defensivo que acaba con el balón nuestro y la recuperación con el rival presionado o tras nuestra pérdida. No cuentan las del portero, las que vienen de un despeje, un rechace o un balón parado del rival, ni las faltas pitadas.",
      "El segundo es el del vídeo táctico del club, atado al de Hudl por tramos; el minuto del detalle es el del partido."
    ],
    "goles": [
      {
        "seg": 967,
        "de": "castilla",
        "texto": "Gol del Castilla"
      },
      {
        "seg": 1943,
        "de": "rival",
        "texto": "Gol del Sant Andreu"
      }
    ],
    "bloquesCerrados": 20,
    "segundosRevisados": 5914,
    "robos": [
      {
        "seg": 90,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "AREA",
        "duracion": 23,
        "pases": "5",
        "detalle": "0'55\" (táctica 1:30) · Recuperación tras pérdida de Thiago Pitarch en campo rival por la izquierda, sigue Thiago Pitarch, acaba en area",
        "confianza": "alta",
        "bloque": "b00000"
      },
      {
        "seg": 227,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 10,
        "pases": "2",
        "detalle": "3'12\" (táctica 3:47) · Recuperación tras pérdida de Mario Rivas en campo propio por la izquierda, sigue Pol Fortuny, acaba en perdida",
        "confianza": "alta",
        "bloque": "b00000"
      },
      {
        "seg": 315,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "FUERA",
        "duracion": 22,
        "pases": "1",
        "detalle": "4'40\" (táctica 5:15) · Interceptación de Mario Rivas en campo propio por el centro, acaba en fuera",
        "confianza": "alta",
        "bloque": "b00300"
      },
      {
        "seg": 525,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "POSESION",
        "duracion": 32,
        "pases": "10",
        "detalle": "8'10\" (táctica 8:45) · Recuperación (pérdida del rival) de Oscar Naasei en campo propio por el centro, acaba en posesion",
        "confianza": "media",
        "bloque": "b00300"
      },
      {
        "seg": 621,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 5,
        "pases": "1",
        "detalle": "9'46\" (táctica 10:21) · Interceptación de Jesús Fortea en campo propio por la derecha, sigue Pol Fortuny, acaba en perdida",
        "confianza": "alta",
        "bloque": "b00600"
      },
      {
        "seg": 663,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 2,
        "pases": "0",
        "detalle": "10'28\" (táctica 11:03) · Interceptación de Mario Rivas en campo propio por el centro, acaba en perdida",
        "confianza": "alta",
        "bloque": "b00600"
      },
      {
        "seg": 750,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 4,
        "pases": "0",
        "detalle": "11'55\" (táctica 12:30) · Duelo ganado de Daniel Yáñez en campo propio por la derecha, acaba en perdida",
        "confianza": "alta",
        "bloque": "b00600"
      },
      {
        "seg": 901,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 45,
        "pases": "14",
        "detalle": "14'26\" (táctica 15:01) · Recuperación con presión de Thiago Pitarch en campo rival por la izquierda, acaba en ultimo tercio",
        "confianza": "media",
        "bloque": "b00900"
      },
      {
        "seg": 967,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "REMATE",
        "duracion": 10,
        "pases": "3",
        "detalle": "15'32\" (táctica 16:07) · Interceptación de Pol Fortuny en medio campo por el centro, acaba en remate de Daniel Yáñez",
        "confianza": "alta",
        "bloque": "b00900"
      },
      {
        "seg": 1073,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 12,
        "pases": "3",
        "detalle": "17'18\" (táctica 17:53) · Duelo ganado de Mario Rivas en medio campo por la derecha, sigue Mario Rivas, acaba en area",
        "confianza": "alta",
        "bloque": "b00900"
      },
      {
        "seg": 1115,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "REMATE",
        "duracion": 17,
        "pases": "4",
        "detalle": "18'00\" (táctica 18:35) · Recuperación con presión de Diego Aguado en campo propio por el centro, acaba en remate de Rachad Fettal",
        "confianza": "media",
        "bloque": "b00900"
      },
      {
        "seg": 1388,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 4,
        "pases": "0",
        "detalle": "22'34\" (táctica 23:08) · Duelo ganado de Diego Aguado en medio campo por la izquierda, acaba en perdida",
        "confianza": "alta",
        "bloque": "b01200"
      },
      {
        "seg": 1495,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 5,
        "pases": "3",
        "detalle": "24'21\" (táctica 24:55) · Recuperación tras pérdida de Jesús Fortea en campo propio por la derecha, acaba en perdida",
        "confianza": "alta",
        "bloque": "b01200"
      },
      {
        "seg": 1541,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "AREA",
        "duracion": 34,
        "pases": "9",
        "detalle": "25'07\" (táctica 25:41) · Recuperación (pérdida del rival) de Pol Fortuny en campo propio por la izquierda, acaba en area",
        "confianza": "media",
        "bloque": "b01500"
      },
      {
        "seg": 1589,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "POSESION",
        "duracion": 25,
        "pases": "12",
        "detalle": "25'54\" (táctica 26:29) · Recuperación (pérdida del rival) de Jesús Fortea en medio campo por la derecha, acaba en posesion",
        "confianza": "media",
        "bloque": "b01500"
      },
      {
        "seg": 1736,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "2",
        "detalle": "28'22\" (táctica 28:56) · Interceptación de Thiago Pitarch en medio campo por la izquierda, acaba en perdida",
        "confianza": "alta",
        "bloque": "b01500"
      },
      {
        "seg": 1763,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 8,
        "pases": "4",
        "detalle": "28'48\" (táctica 29:23) · Recuperación tras pérdida de Thiago Pitarch en medio campo por la izquierda, acaba en perdida",
        "confianza": "alta",
        "bloque": "b01500"
      },
      {
        "seg": 1775,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "1",
        "detalle": "29'00\" (táctica 29:35) · Recuperación tras pérdida de Jesús Fortea en medio campo por la derecha, sigue Oscar Naasei, acaba en perdida",
        "confianza": "alta",
        "bloque": "b01500"
      },
      {
        "seg": 1801,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 36,
        "pases": "4",
        "detalle": "29'27\" (táctica 30:01) · Recuperación con presión de Oscar Naasei en medio campo por el centro, sigue Mario Rivas, acaba en ultimo tercio",
        "confianza": "media",
        "bloque": "b01800"
      },
      {
        "seg": 1864,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 2,
        "pases": "2",
        "detalle": "30'30\" (táctica 31:04) · Recuperación (pérdida del rival) de Oscar Naasei en medio campo por el centro, acaba en perdida",
        "confianza": "media",
        "bloque": "b01800"
      },
      {
        "seg": 1869,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "REMATE",
        "duracion": 5,
        "pases": "2",
        "detalle": "30'34\" (táctica 31:09) · Recuperación tras pérdida de Martínez en medio campo por la izquierda, acaba en remate de Jesús Fortea",
        "confianza": "alta",
        "bloque": "b01800"
      },
      {
        "seg": 2108,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 5,
        "pases": "1",
        "detalle": "35'33\" (táctica 35:08) · Recuperación tras pérdida de Martínez en medio campo por el centro, sigue Martínez, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b02100"
      },
      {
        "seg": 2246,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "FALTA_CONTRA",
        "duracion": 2,
        "pases": "1",
        "detalle": "37'51\" (táctica 37:26) · Recuperación tras pérdida de Mario Rivas en campo propio por el centro, acaba en falta contra",
        "confianza": "alta",
        "bloque": "b02100"
      },
      {
        "seg": 2398,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 6,
        "pases": "1",
        "detalle": "40'23\" (táctica 39:58) · Interceptación de Diego Aguado en campo rival por la izquierda, sigue Mario Rivas, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b02100"
      },
      {
        "seg": 2546,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 32,
        "pases": "3",
        "detalle": "42'50\" (táctica 42:26) · Interceptación de Thiago Pitarch en medio campo por el centro, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b02400"
      },
      {
        "seg": 2695,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 2,
        "pases": "2",
        "detalle": "45+0'19\" (táctica 44:55) · Recuperación tras pérdida de Oscar Naasei en campo propio por el centro, acaba en perdida",
        "confianza": "alta",
        "bloque": "b02400"
      },
      {
        "seg": 2702,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 41,
        "pases": "13",
        "detalle": "45+0'27\" (táctica 45:02) · Recuperación tras pérdida de Oscar Naasei en medio campo por el centro, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b02700"
      },
      {
        "seg": 2755,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "REMATE",
        "duracion": 11,
        "pases": "4",
        "detalle": "45+1'20\" (táctica 45:55) · Recuperación tras pérdida de Pol Fortuny en medio campo por el centro, acaba en remate de Martínez",
        "confianza": "alta",
        "bloque": "b02700"
      },
      {
        "seg": 2903,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "POSESION",
        "duracion": 36,
        "pases": "12",
        "detalle": "45'12\" (táctica 48:23) · Recuperación (pérdida del rival) de Oscar Naasei en medio campo por el centro, acaba en posesion",
        "confianza": "media",
        "bloque": "b02700"
      },
      {
        "seg": 3040,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "FUERA",
        "duracion": 21,
        "pases": "4",
        "detalle": "47'29\" (táctica 50:40) · Recuperación (pérdida del rival) de Jesús Fortea en medio campo por la derecha, acaba en fuera",
        "confianza": "media",
        "bloque": "b03000"
      },
      {
        "seg": 3073,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 0,
        "pases": "1",
        "detalle": "48'03\" (táctica 51:13) · Recuperación con presión de Pol Fortuny en campo rival por la derecha, sigue Pol Fortuny, acaba en area",
        "confianza": "media",
        "bloque": "b03000"
      },
      {
        "seg": 3136,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 40,
        "pases": "13",
        "detalle": "49'05\" (táctica 52:16) · Recuperación tras pérdida de Jesús Fortea en campo propio por la derecha, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b03000"
      },
      {
        "seg": 3204,
        "zona": "campo rival",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "REMATE",
        "duracion": 13,
        "pases": "5",
        "detalle": "50'14\" (táctica 53:24) · Recuperación tras pérdida de Diego Aguado en campo rival por el centro, acaba en remate de Rachad Fettal",
        "confianza": "alta",
        "bloque": "b03000"
      },
      {
        "seg": 3255,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 44,
        "pases": "15",
        "detalle": "51'05\" (táctica 54:15) · Recuperación (pérdida del rival) de Mario Rivas en campo propio por el centro, acaba en ultimo tercio",
        "confianza": "media",
        "bloque": "b03000"
      },
      {
        "seg": 3386,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 32,
        "pases": "11",
        "detalle": "53'16\" (táctica 56:26) · Recuperación tras pérdida de Martínez en medio campo por el centro, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b03300"
      },
      {
        "seg": 3996,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "REMATE",
        "duracion": 11,
        "pases": "3",
        "detalle": "63'26\" (táctica 66:36) · Recuperación (pérdida del rival) de Daniel Yáñez en medio campo por el centro, acaba en remate de Daniel Yáñez",
        "confianza": "media",
        "bloque": "b03900"
      },
      {
        "seg": 4079,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 44,
        "pases": "14",
        "detalle": "64'48\" (táctica 67:59) · Recuperación tras pérdida de Jesús Fortea en campo rival por la derecha, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b03900"
      },
      {
        "seg": 4196,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 23,
        "pases": "7",
        "detalle": "66'46\" (táctica 69:56) · Recuperación (pérdida del rival) de Mario Rivas en medio campo por la izquierda, acaba en ultimo tercio",
        "confianza": "media",
        "bloque": "b03900"
      },
      {
        "seg": 4231,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 15,
        "pases": "4",
        "detalle": "67'21\" (táctica 70:31) · Duelo ganado de Jesús Fortea en campo rival por la derecha, sigue Pol Fortuny, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b04200"
      },
      {
        "seg": 4347,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 42,
        "pases": "12",
        "detalle": "69'17\" (táctica 72:27) · Interceptación de Mario Rivas en campo propio por el centro, sigue Roberto Martín, acaba en area",
        "confianza": "alta",
        "bloque": "b04200"
      },
      {
        "seg": 4416,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "0",
        "detalle": "70'26\" (táctica 73:36) · Interceptación de Mario Rivas en medio campo por la izquierda, acaba en perdida",
        "confianza": "alta",
        "bloque": "b04200"
      },
      {
        "seg": 4422,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ATRAS_PORTERO",
        "duracion": 3,
        "pases": "2",
        "detalle": "70'31\" (táctica 73:42) · Interceptación de Jesús Fortea en medio campo por el centro, acaba en atras portero",
        "confianza": "alta",
        "bloque": "b04200"
      },
      {
        "seg": 4585,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 44,
        "pases": "11",
        "detalle": "73'14\" (táctica 76:25) · Duelo ganado de Dani Meso en medio campo por la izquierda, sigue Martínez, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b04500"
      },
      {
        "seg": 4847,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 19,
        "pases": "3",
        "detalle": "77'36\" (táctica 80:47) · Recuperación (pérdida del rival) de Jesús Fortea en campo propio por la derecha, acaba en area",
        "confianza": "media",
        "bloque": "b04800"
      },
      {
        "seg": 4871,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "REMATE",
        "duracion": 2,
        "pases": "1",
        "detalle": "78'00\" (táctica 81:11) · Recuperación tras pérdida de Diego Aguado en campo rival por la izquierda, acaba en remate de Dani Meso",
        "confianza": "alta",
        "bloque": "b04800"
      },
      {
        "seg": 5469,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "1",
        "detalle": "88'44\" (táctica 91:09) · Interceptación de Oscar Naasei en campo propio por el centro, sigue Jorge Rajado, acaba en perdida",
        "confianza": "alta",
        "bloque": "b05400"
      },
      {
        "seg": 5478,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "1",
        "detalle": "88'52\" (táctica 91:18) · Recuperación tras pérdida de Martínez en campo propio por el centro, acaba en perdida",
        "confianza": "alta",
        "bloque": "b05400"
      },
      {
        "seg": 5499,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "DESPEJE",
        "desenlace": "PERDIDA",
        "duracion": 9,
        "pases": "3",
        "detalle": "89'13\" (táctica 91:39) · Interceptación de Oscar Naasei en campo propio por el centro, sigue Mario Rivas, acaba en perdida",
        "confianza": "alta",
        "bloque": "b05400"
      },
      {
        "seg": 5559,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "2",
        "detalle": "90+0'13\" (táctica 92:39) · Interceptación de Oscar Naasei en campo propio por el centro, sigue Martínez, acaba en perdida",
        "confianza": "alta",
        "bloque": "b05400"
      },
      {
        "seg": 5572,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "1",
        "detalle": "90+0'26\" (táctica 92:52) · Interceptación de Dani Meso en campo propio por el centro, sigue Jesús Fortea, acaba en perdida",
        "confianza": "alta",
        "bloque": "b05400"
      },
      {
        "seg": 5699,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 13,
        "pases": "3",
        "detalle": "90+2'34\" (táctica 94:59) · Duelo ganado de Diego Aguado en campo propio por la izquierda, sigue Diego Aguado, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b05400"
      },
      {
        "seg": 5783,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 37,
        "pases": "9",
        "detalle": "90+3'58\" (táctica 96:23) · Recuperación (pérdida del rival) de Mario Rivas en medio campo por la izquierda, acaba en ultimo tercio",
        "confianza": "media",
        "bloque": "b05700"
      }
    ]
  },
  {
    "id": "alcorcon",
    "jornada": "J5",
    "rival": "AD Alcorcón",
    "local": true,
    "fecha": "2026-09-27",
    "resultado": "1-2",
    "video": "C:/Users/Usuario/Downloads/CASTILLA - ALCORCON.mov",
    "segundosVideo": 6082,
    "bloquesTotales": 21,
    "notas": [
      "Sacado del timeline de Hudl (el etiquetado de Wyscout del partido), no mirando imagen a imagen: salen TODOS los robos del partido, también los cortos que a ojo se escapaban. Por eso hay más que en el J2 y el J3, y el reparto no se compara con ellos sin decirlo.",
      "Cuenta como robo la interceptación, el duelo defensivo que acaba con el balón nuestro y la recuperación con el rival presionado o tras nuestra pérdida. No cuentan las del portero, las que vienen de un despeje, un rechace o un balón parado del rival, ni las faltas pitadas.",
      "El segundo es el del vídeo táctico del club. Esa grabación tiene cortes: el desfase con el reloj del partido cambia tres veces (medido jugada a jugada), así que en algún robo el vídeo puede caer unos segundos antes o después."
    ],
    "goles": [
      {
        "seg": 702,
        "de": "castilla",
        "texto": "Gol del Castilla, de penalti (Fortuny)"
      },
      {
        "seg": 2281,
        "de": "rival",
        "texto": "Gol del Alcorcón, de cabeza tras un córner (Mayorga)"
      },
      {
        "seg": 2670,
        "de": "rival",
        "texto": "Gol del Alcorcón (Aparicio)"
      }
    ],
    "bloquesCerrados": 21,
    "segundosRevisados": 6082,
    "robos": [
      {
        "seg": 34,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "POSESION",
        "duracion": 27,
        "pases": "10",
        "detalle": "0'27\" (táctica 0:34) · Recuperación (pérdida del rival) de Oscar Naasei en medio campo por el centro, acaba en posesion",
        "confianza": "media",
        "bloque": "b00000"
      },
      {
        "seg": 67,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "AREA",
        "duracion": 33,
        "pases": "3",
        "detalle": "1'00\" (táctica 1:07) · Recuperación tras pérdida de Diego Aguado en medio campo por el centro, sigue Pol Fortuny, acaba en area",
        "confianza": "alta",
        "bloque": "b00000"
      },
      {
        "seg": 190,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "0",
        "detalle": "3'03\" (táctica 3:10) · Interceptación de Joan Martínez en campo propio por la izquierda, acaba en perdida",
        "confianza": "baja",
        "bloque": "b00000"
      },
      {
        "seg": 325,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 2,
        "pases": "2",
        "detalle": "5'18\" (táctica 5:25) · Recuperación (pérdida del rival) de Martínez en medio campo por el centro, acaba en ultimo tercio",
        "confianza": "media",
        "bloque": "b00300"
      },
      {
        "seg": 772,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "DESPEJE",
        "desenlace": "FUERA",
        "duracion": 12,
        "pases": "0",
        "detalle": "12'45\" (táctica 12:52) · Interceptación de Oscar Naasei en campo propio por la derecha, sigue Jesús Fortea, acaba en fuera",
        "confianza": "alta",
        "bloque": "b00600"
      },
      {
        "seg": 845,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "POSESION",
        "duracion": 20,
        "pases": "9",
        "detalle": "13'58\" (táctica 14:05) · Recuperación con presión de Álvaro Leiva en medio campo por el centro, acaba en posesion",
        "confianza": "media",
        "bloque": "b00600"
      },
      {
        "seg": 948,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "AREA",
        "duracion": 26,
        "pases": "8",
        "detalle": "15'41\" (táctica 15:48) · Recuperación (pérdida del rival) de Thiago Pitarch en medio campo por el centro, acaba en area",
        "confianza": "media",
        "bloque": "b00900"
      },
      {
        "seg": 1014,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 15,
        "pases": "4",
        "detalle": "16'47\" (táctica 16:54) · Duelo ganado de Jesús Fortea en medio campo por la derecha, sigue Oscar Naasei, acaba en perdida",
        "confianza": "alta",
        "bloque": "b00900"
      },
      {
        "seg": 1035,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "REMATE",
        "duracion": 14,
        "pases": "3",
        "detalle": "17'08\" (táctica 17:15) · Interceptación de Oscar Naasei en medio campo por la derecha, acaba en remate de Ángel Carvajal",
        "confianza": "alta",
        "bloque": "b00900"
      },
      {
        "seg": 1155,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 12,
        "pases": "3",
        "detalle": "19'08\" (táctica 19:15) · Recuperación (pérdida del rival) de Oscar Naasei en campo propio por el centro, acaba en perdida",
        "confianza": "media",
        "bloque": "b00900"
      },
      {
        "seg": 1184,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 2,
        "pases": "0",
        "detalle": "19'37\" (táctica 19:44) · Interceptación de Ángel Carvajal en campo rival por la derecha, acaba en perdida",
        "confianza": "alta",
        "bloque": "b00900"
      },
      {
        "seg": 1189,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "AREA",
        "duracion": 1,
        "pases": "1",
        "detalle": "19'42\" (táctica 19:49) · Recuperación tras pérdida de Jesús Fortea en campo rival por la derecha, acaba en area",
        "confianza": "alta",
        "bloque": "b00900"
      },
      {
        "seg": 1242,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "0",
        "detalle": "20'35\" (táctica 20:42) · Interceptación de Martínez en medio campo por la derecha, acaba en perdida",
        "confianza": "baja",
        "bloque": "b01200"
      },
      {
        "seg": 1305,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "PERDIDA",
        "desenlace": "FUERA",
        "duracion": 12,
        "pases": "0",
        "detalle": "21'38\" (táctica 21:45) · Interceptación de Thiago Pitarch en medio campo por la derecha, acaba en fuera",
        "confianza": "alta",
        "bloque": "b01200"
      },
      {
        "seg": 1358,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 45,
        "pases": "9",
        "detalle": "22'31\" (táctica 22:38) · Recuperación con presión de Diego Aguado en campo propio por el centro, sigue Álvaro Leiva, acaba en ultimo tercio",
        "confianza": "media",
        "bloque": "b01200"
      },
      {
        "seg": 1409,
        "zona": "campo rival",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 3,
        "pases": "2",
        "detalle": "23'22\" (táctica 23:29) · Recuperación tras pérdida de Martínez en campo rival por el centro, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b01200"
      },
      {
        "seg": 1634,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 6,
        "pases": "2",
        "detalle": "27'07\" (táctica 27:14) · Interceptación de Diego Aguado en campo propio por la izquierda, sigue Diego Aguado, acaba en perdida",
        "confianza": "alta",
        "bloque": "b01500"
      },
      {
        "seg": 1693,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 16,
        "pases": "3",
        "detalle": "28'06\" (táctica 28:13) · Interceptación de Daniel Yáñez en campo propio por el centro, sigue Ángel Carvajal, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b01500"
      },
      {
        "seg": 1766,
        "zona": "campo rival",
        "carril": "centro",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "0",
        "detalle": "29'19\" (táctica 29:26) · Interceptación de Álvaro Leiva en campo rival por el centro, acaba en perdida",
        "confianza": "baja",
        "bloque": "b01500"
      },
      {
        "seg": 1775,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "POSESION",
        "duracion": 19,
        "pases": "5",
        "detalle": "29'28\" (táctica 29:35) · Recuperación (pérdida del rival) de Martínez en medio campo por el centro, acaba en posesion",
        "confianza": "media",
        "bloque": "b01500"
      },
      {
        "seg": 1971,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "0",
        "detalle": "33'14\" (táctica 32:51) · Interceptación de Martínez en campo propio por la derecha, acaba en perdida",
        "confianza": "baja",
        "bloque": "b01800"
      },
      {
        "seg": 2127,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 2,
        "pases": "0",
        "detalle": "35'51\" (táctica 35:27) · Interceptación de Martínez en campo propio por la izquierda, acaba en perdida",
        "confianza": "alta",
        "bloque": "b02100"
      },
      {
        "seg": 2143,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "1",
        "detalle": "36'06\" (táctica 35:43) · Recuperación tras pérdida de Pol Fortuny en campo propio por la derecha, sigue Oscar Naasei, acaba en perdida",
        "confianza": "alta",
        "bloque": "b02100"
      },
      {
        "seg": 2425,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 5,
        "pases": "2",
        "detalle": "40'48\" (táctica 40:25) · Recuperación (pérdida del rival) de Oscar Naasei en campo propio por el centro, acaba en perdida",
        "confianza": "media",
        "bloque": "b02400"
      },
      {
        "seg": 2811,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 6,
        "pases": "3",
        "detalle": "45+2'15\" (táctica 46:51) · Recuperación (pérdida del rival) de Joan Martínez en campo propio por la izquierda, acaba en perdida",
        "confianza": "media",
        "bloque": "b02700"
      },
      {
        "seg": 3112,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 4,
        "pases": "3",
        "detalle": "45'29\" (táctica 51:52) · Recuperación (pérdida del rival) de Daniel Yáñez en medio campo por la derecha, acaba en perdida",
        "confianza": "media",
        "bloque": "b03000"
      },
      {
        "seg": 3237,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 4,
        "pases": "3",
        "detalle": "47'33\" (táctica 53:57) · Recuperación tras pérdida de Oscar Naasei en campo propio por el centro, acaba en perdida",
        "confianza": "alta",
        "bloque": "b03000"
      },
      {
        "seg": 3421,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "FALTA_CONTRA",
        "duracion": 5,
        "pases": "1",
        "detalle": "50'38\" (táctica 57:01) · Interceptación de Daniel Yáñez en medio campo por la derecha, sigue Daniel Yáñez, acaba en falta contra",
        "confianza": "alta",
        "bloque": "b03300"
      },
      {
        "seg": 3646,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "2",
        "detalle": "54'23\" (táctica 60:46) · Recuperación (pérdida del rival) de Martínez en medio campo por la derecha, acaba en perdida",
        "confianza": "media",
        "bloque": "b03600"
      },
      {
        "seg": 3739,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 8,
        "pases": "1",
        "detalle": "55'56\" (táctica 62:19) · Recuperación tras pérdida de Thiago Pitarch en medio campo por la izquierda, acaba en area",
        "confianza": "alta",
        "bloque": "b03600"
      },
      {
        "seg": 3879,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 4,
        "pases": "0",
        "detalle": "58'15\" (táctica 64:39) · Recuperación con presión de Thiago Pitarch en medio campo por el centro, sigue Álvaro Leiva, acaba en perdida",
        "confianza": "media",
        "bloque": "b03600"
      },
      {
        "seg": 4032,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 2,
        "pases": "2",
        "detalle": "60'48\" (táctica 67:12) · Recuperación (pérdida del rival) de Joan Martínez en campo propio por el centro, acaba en perdida",
        "confianza": "media",
        "bloque": "b03900"
      },
      {
        "seg": 4099,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 33,
        "pases": "11",
        "detalle": "61'56\" (táctica 68:19) · Recuperación (pérdida del rival) de Oscar Naasei en medio campo por la derecha, acaba en ultimo tercio",
        "confianza": "media",
        "bloque": "b03900"
      },
      {
        "seg": 4224,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 7,
        "pases": "3",
        "detalle": "64'01\" (táctica 70:24) · Recuperación (pérdida del rival) de Dani Meso en medio campo por el centro, acaba en ultimo tercio",
        "confianza": "media",
        "bloque": "b04200"
      },
      {
        "seg": 4253,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 2,
        "pases": "2",
        "detalle": "64'30\" (táctica 70:53) · Recuperación (pérdida del rival) de Dani Meso en campo rival por la derecha, acaba en area",
        "confianza": "media",
        "bloque": "b04200"
      },
      {
        "seg": 4596,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "1",
        "detalle": "70'13\" (táctica 76:36) · Duelo ganado de Joan Martínez en medio campo por el centro, sigue Joan Martínez, acaba en perdida",
        "confianza": "alta",
        "bloque": "b04500"
      },
      {
        "seg": 4635,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 2,
        "pases": "1",
        "detalle": "70'52\" (táctica 77:15) · Recuperación tras pérdida de Diego Aguado en campo rival por la izquierda, sigue Thiago Pitarch, acaba en area",
        "confianza": "alta",
        "bloque": "b04500"
      },
      {
        "seg": 4859,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 14,
        "pases": "5",
        "detalle": "74'36\" (táctica 80:59) · Recuperación (pérdida del rival) de Jesús Fortea en campo rival por la derecha, acaba en ultimo tercio",
        "confianza": "media",
        "bloque": "b04800"
      },
      {
        "seg": 5178,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 4,
        "pases": "3",
        "detalle": "80'31\" (táctica 86:18) · Interceptación de Dani Meso en campo propio por la derecha, acaba en perdida",
        "confianza": "alta",
        "bloque": "b05100"
      },
      {
        "seg": 5200,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "POSESION",
        "duracion": 20,
        "pases": "7",
        "detalle": "80'54\" (táctica 86:40) · Recuperación (pérdida del rival) de Mario Rivas en medio campo por la derecha, acaba en posesion",
        "confianza": "media",
        "bloque": "b05100"
      },
      {
        "seg": 5233,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 5,
        "pases": "2",
        "detalle": "81'26\" (táctica 87:13) · Recuperación (pérdida del rival) de Jesús Fortea en campo propio por la derecha, acaba en perdida",
        "confianza": "media",
        "bloque": "b05100"
      },
      {
        "seg": 5483,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 22,
        "pases": "6",
        "detalle": "85'37\" (táctica 91:23) · Interceptación de Dani Meso en medio campo por la derecha, sigue Oscar Naasei, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b05400"
      },
      {
        "seg": 5666,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 11,
        "pases": "3",
        "detalle": "88'40\" (táctica 94:26) · Recuperación tras pérdida de Roberto Martín en campo propio por el centro, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b05400"
      },
      {
        "seg": 5753,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ATRAS_PORTERO",
        "duracion": 3,
        "pases": "2",
        "detalle": "90+0'06\" (táctica 95:53) · Recuperación tras pérdida de Oscar Naasei en campo propio por la derecha, acaba en atras portero",
        "confianza": "alta",
        "bloque": "b05700"
      },
      {
        "seg": 5790,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "REMATE",
        "duracion": 10,
        "pases": "4",
        "detalle": "90+0'44\" (táctica 96:30) · Interceptación de Mario Rivas en medio campo por la derecha, acaba en remate de Alexis Ciria",
        "confianza": "alta",
        "bloque": "b05700"
      },
      {
        "seg": 5808,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 8,
        "pases": "3",
        "detalle": "90+1'01\" (táctica 96:48) · Recuperación (pérdida del rival) de Joan Martínez en medio campo por la izquierda, acaba en ultimo tercio",
        "confianza": "media",
        "bloque": "b05700"
      },
      {
        "seg": 5939,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ATRAS_PORTERO",
        "duracion": 4,
        "pases": "2",
        "detalle": "90+3'12\" (táctica 98:59) · Recuperación (pérdida del rival) de Joan Martínez en medio campo por la izquierda, acaba en atras portero",
        "confianza": "media",
        "bloque": "b05700"
      }
    ]
  },
  {
    "jornada": "J6",
    "rival": "Atlético Madrileño",
    "local": true,
    "fecha": "2026-10-02",
    "resultado": "3-2",
    "video": "C:/Users/Usuario/Downloads/RMCF CASTILLA/PARTIDOS/J 06 -CASTILLA - ATL. MADRILEÑO.mov",
    "segundosVideo": 6424,
    "bloquesTotales": 22,
    "notas": [
      "Sacado del timeline de Hudl (el etiquetado de Wyscout del partido), no mirando imagen a imagen: salen TODOS los robos del partido.",
      "Cuenta como robo la interceptación, el duelo defensivo que acaba con el balón nuestro y la recuperación con el rival presionado o tras nuestra pérdida. No cuentan las del portero, las que vienen de un despeje, un rechace o un balón parado del rival, ni las faltas pitadas.",
      "El segundo es el del vídeo táctico del club, atado al de Hudl por tramos medidos jugada a jugada.",
      "Vídeo táctico (dron) de 6424 s. Desfase táctica − Hudl medido con córners, penaltis y jugadas revisadas: +49/+51 s en toda la 1ª parte.",
      "Hacia el seg 3020-3085 de la táctica el dron aterriza (plano desde el suelo y pared del almacén): se pierde el final de la 1ª parte; la 2ª parte arranca con desfase +128 s que crece hasta +134 s (seg 4078, penalti del 2-1).",
      "Corte hacia el seg 4245 de la táctica (cambio a plano lejano nocturno): desfase +76 s; llega a +78 s hacia el min 80-95.",
      "Corte hacia el seg 6162 de la táctica (plano nocturno lejano): se pierden unos 45 s del juego (Hudl 6090-6130, incluido el saque de banda del Castilla del 96:44); desde ahí desfase +35 s hasta el final (córners del descuento en los seg 6353 y 6383).",
      "Orientación en la táctica: en las dos partes el Castilla ataca la portería de arriba (lejana) y defiende la de abajo (cercana): el dron cambia de fondo en el descanso. En la TV el Castilla ataca hacia la izquierda en la 1ª parte y hacia la derecha en la 2ª.",
      "Castilla de blanco; Atlético Madrileño con rayas rojiblancas y pantalón azul."
    ],
    "goles": [
      {
        "seg": 551,
        "de": "castilla",
        "texto": "1-0 (min 9). Gol del Castilla en jugada (Hudl: posesión de Mario Rivas y Ángel Carvajal). Segundo aproximado (±3 s): fin de la jugada de Hudl + desfase."
      },
      {
        "seg": 2765,
        "de": "rival",
        "texto": "1-1 (min 45+1). Gol del Atlético Madrileño tras una posesión larga desde su portero (45 s). Segundo aproximado (±3 s)."
      },
      {
        "seg": 4078,
        "de": "castilla",
        "texto": "2-1 (min 61). Penalti de Aguado, raso a la derecha del portero; Astralaga se tira al otro lado. Visto en la táctica."
      },
      {
        "seg": 4352,
        "de": "rival",
        "texto": "2-2 (min 66). Penalti de David Hidalgo que para Mestre; Koke marca al rechace. Penalti en el seg 4340 de la táctica; gol aproximado."
      },
      {
        "seg": 4633,
        "de": "castilla",
        "texto": "3-2 (min 71). Gol del Castilla en una transición larga desde Mestre (Naasei, Cestero, Pitarch, Leiva, Carvajal, Fortea, Yáñez). Segundo aproximado (±3 s)."
      }
    ],
    "id": "j06-atletico-madrileno",
    "bloquesCerrados": 22,
    "segundosRevisados": 6424,
    "robos": [
      {
        "seg": 60,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "0",
        "detalle": "0'10\" (táctica 1:00) · Interceptación de Álvaro Leiva en campo rival por la izquierda, acaba en perdida",
        "confianza": "baja",
        "bloque": "b00000"
      },
      {
        "seg": 188,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "AREA",
        "duracion": 21,
        "pases": "5",
        "detalle": "2'17\" (táctica 3:08) · Duelo ganado de Daniel Yáñez en medio campo por el centro, sigue Oscar Naasei, acaba en area",
        "confianza": "alta",
        "bloque": "b00000"
      },
      {
        "seg": 402,
        "zona": "medio campo",
        "carril": "centro",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 2,
        "pases": "0",
        "detalle": "5'52\" (táctica 6:42) · Recuperación tras pérdida de Álvaro Leiva en medio campo por el centro, acaba en perdida",
        "confianza": "alta",
        "bloque": "b00300"
      },
      {
        "seg": 771,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "DESPEJE",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "0",
        "detalle": "12'00\" (táctica 12:51) · Recuperación con presión de Martínez en medio campo por la derecha, sigue Oscar Naasei, acaba en perdida",
        "confianza": "media",
        "bloque": "b00600"
      },
      {
        "seg": 1475,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "AREA",
        "duracion": 23,
        "pases": "8",
        "detalle": "23'42\" (táctica 24:35) · Recuperación (pérdida del rival) de Jesús Fortea en campo propio por la derecha, acaba en area",
        "confianza": "media",
        "bloque": "b01200"
      },
      {
        "seg": 1504,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 40,
        "pases": "13",
        "detalle": "24'12\" (táctica 25:04) · Recuperación tras pérdida de Álvaro Leiva en campo rival por la izquierda, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b01500"
      },
      {
        "seg": 1553,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "REMATE",
        "duracion": 20,
        "pases": "6",
        "detalle": "25'01\" (táctica 25:53) · Recuperación (pérdida del rival) de Álvaro Leiva en campo rival por la izquierda, acaba en remate de Álvaro Leiva",
        "confianza": "media",
        "bloque": "b01500"
      },
      {
        "seg": 1751,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 42,
        "pases": "14",
        "detalle": "28'18\" (táctica 29:11) · Interceptación de Oscar Naasei en medio campo por la derecha, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b01500"
      },
      {
        "seg": 1890,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "0",
        "detalle": "30'37\" (táctica 31:30) · Interceptación de Diego Aguado en campo propio por la izquierda, acaba en perdida",
        "confianza": "baja",
        "bloque": "b01800"
      },
      {
        "seg": 1949,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 7,
        "pases": "2",
        "detalle": "31'36\" (táctica 32:29) · Interceptación de Mario Rivas en campo propio por el centro, sigue Álvaro Leiva, acaba en perdida",
        "confianza": "alta",
        "bloque": "b01800"
      },
      {
        "seg": 1995,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ATRAS_PORTERO",
        "duracion": 10,
        "pases": "2",
        "detalle": "32'22\" (táctica 33:15) · Interceptación de Álvaro Leiva en campo propio por la izquierda, acaba en atras portero",
        "confianza": "alta",
        "bloque": "b01800"
      },
      {
        "seg": 2307,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 7,
        "pases": "2",
        "detalle": "37'34\" (táctica 38:27) · Duelo ganado de Daniel Yáñez en campo propio por la derecha, sigue Daniel Yáñez, acaba en area",
        "confianza": "alta",
        "bloque": "b02100"
      },
      {
        "seg": 2585,
        "zona": "medio campo",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 11,
        "pases": "2",
        "detalle": "42'13\" (táctica 43:05) · Interceptación de Martínez en medio campo por la derecha, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b02400"
      },
      {
        "seg": 2656,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "REMATE",
        "duracion": 37,
        "pases": "8",
        "detalle": "43'23\" (táctica 44:16) · Duelo ganado de Ángel Carvajal en campo propio por el centro, sigue Martínez, acaba en remate de Jesús Fortea",
        "confianza": "alta",
        "bloque": "b02400"
      },
      {
        "seg": 2868,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "FUERA",
        "duracion": 14,
        "pases": "2",
        "detalle": "45+1'55\" (táctica 47:48) · Recuperación (pérdida del rival) de Mario Rivas en campo propio por la izquierda, acaba en fuera",
        "confianza": "media",
        "bloque": "b02700"
      },
      {
        "seg": 2908,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "DESPEJE",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "0",
        "detalle": "45+2'36\" (táctica 48:28) · Duelo ganado de Diego Aguado en campo propio por el centro, sigue Oscar Naasei, acaba en perdida",
        "confianza": "alta",
        "bloque": "b02700"
      },
      {
        "seg": 3175,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "REMATE",
        "duracion": 3,
        "pases": "2",
        "detalle": "45'31\" (táctica 52:55) · Recuperación tras pérdida de Jesús Fortea en campo rival por la derecha, acaba en remate de Ángel Carvajal",
        "confianza": "alta",
        "bloque": "b03000"
      },
      {
        "seg": 3328,
        "zona": "campo rival",
        "carril": "centro",
        "accion": "PERDIDA",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "0",
        "detalle": "48'04\" (táctica 55:28) · Interceptación de Álvaro Leiva en campo rival por el centro, acaba en perdida",
        "confianza": "baja",
        "bloque": "b03300"
      },
      {
        "seg": 3445,
        "zona": "medio campo",
        "carril": "izquierda",
        "accion": "ADELANTE",
        "desenlace": "AREA",
        "duracion": 20,
        "pases": "6",
        "detalle": "49'59\" (táctica 57:25) · Recuperación (pérdida del rival) de Jorge Cestero en medio campo por la izquierda, acaba en area",
        "confianza": "media",
        "bloque": "b03300"
      },
      {
        "seg": 3584,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "DESPEJE",
        "desenlace": "PERDIDA",
        "duracion": 3,
        "pases": "0",
        "detalle": "52'18\" (táctica 59:44) · Interceptación de Mario Rivas en campo propio por el centro, sigue Mario Rivas, acaba en perdida",
        "confianza": "alta",
        "bloque": "b03300"
      },
      {
        "seg": 4530,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "PERDIDA",
        "duracion": 1,
        "pases": "0",
        "detalle": "68'59\" (táctica 75:30) · Recuperación tras pérdida de Oscar Naasei en campo propio por la derecha, acaba en perdida",
        "confianza": "alta",
        "bloque": "b04500"
      },
      {
        "seg": 4536,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 44,
        "pases": "16",
        "detalle": "69'05\" (táctica 75:36) · Recuperación tras pérdida de Oscar Naasei en campo propio por la derecha, acaba en ultimo tercio",
        "confianza": "alta",
        "bloque": "b04500"
      },
      {
        "seg": 5329,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "FALTA_FAVOR",
        "duracion": 2,
        "pases": "1",
        "detalle": "82'16\" (táctica 88:49) · Interceptación de Mario Rivas en campo propio por el centro, acaba en falta favor",
        "confianza": "alta",
        "bloque": "b05100"
      },
      {
        "seg": 5432,
        "zona": "campo propio",
        "carril": "derecha",
        "accion": "ADELANTE",
        "desenlace": "ULTIMO_TERCIO",
        "duracion": 8,
        "pases": "3",
        "detalle": "83'59\" (táctica 90:32) · Recuperación (pérdida del rival) de Oscar Naasei en campo propio por la derecha, acaba en ultimo tercio",
        "confianza": "media",
        "bloque": "b05400"
      },
      {
        "seg": 5451,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "PERDIDA",
        "duracion": 10,
        "pases": "3",
        "detalle": "84'18\" (táctica 90:51) · Recuperación con presión de Álvaro Lezcano en campo propio por el centro, acaba en perdida",
        "confianza": "media",
        "bloque": "b05400"
      },
      {
        "seg": 5693,
        "zona": "campo rival",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "FUERA",
        "duracion": 11,
        "pases": "2",
        "detalle": "88'20\" (táctica 94:53) · Recuperación tras pérdida de Álvaro Lezcano en campo rival por la izquierda, acaba en fuera",
        "confianza": "alta",
        "bloque": "b05400"
      },
      {
        "seg": 5795,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "ADELANTE",
        "desenlace": "FUERA",
        "duracion": 21,
        "pases": "1",
        "detalle": "90+0'01\" (táctica 96:35) · Recuperación (pérdida del rival) de Oscar Naasei en campo propio por el centro, acaba en fuera",
        "confianza": "media",
        "bloque": "b05700"
      },
      {
        "seg": 6071,
        "zona": "campo propio",
        "carril": "izquierda",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "AREA",
        "duracion": 15,
        "pases": "3",
        "detalle": "90+4'37\" (táctica 101:11) · Duelo ganado de Álvaro Lezcano en campo propio por la izquierda, sigue Álvaro Lezcano, acaba en area",
        "confianza": "alta",
        "bloque": "b06000"
      },
      {
        "seg": 6090,
        "zona": "campo rival",
        "carril": "derecha",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "AREA",
        "duracion": 14,
        "pases": "5",
        "detalle": "90+4'57\" (táctica 101:30) · Recuperación tras pérdida de Alexis Ciria en campo rival por la derecha, acaba en area",
        "confianza": "alta",
        "bloque": "b06000"
      },
      {
        "seg": 6253,
        "zona": "campo propio",
        "carril": "centro",
        "accion": "HORIZONTAL_ATRAS",
        "desenlace": "FALTA_FAVOR",
        "duracion": 3,
        "pases": "1",
        "detalle": "90+8'23\" (táctica 104:13) · Duelo ganado de Roberto Martín en campo propio por el centro, sigue Thiago Pitarch, acaba en falta favor",
        "confianza": "alta",
        "bloque": "b06000"
      }
    ]
  }
];
