export interface WeekData {
  id: number;
  month: string;
  week: string;
  start: string;
  end: string;
  images: string[];
  pdf?: string;
}

export interface MonthData {
  id: number;
  name: string;
  weeks: WeekData[];
}

export const season: MonthData[] = [
  {
    id: 1,
    name: "Julio",
    weeks: [
      {
        id: 1,
        month: "Julio",
        week: "Semana 1",
        start: "1 Jul",
        end: "5 Jul",
        images: [
          "/IMG-20260709-WA0010.jpg",
          "/IMG-20260708-WA0001.jpg",
          "/IMG-20260709-WA0011.jpg",
        ],
        pdf: "",
      },
      {
        id: 2,
        month: "Julio",
        week: "Semana 2",
        start: "6 Jul",
        end: "12 Jul",
        images: [],
        pdf: "",
      },
      {
        id: 3,
        month: "Julio",
        week: "Semana 3",
        start: "13 Jul",
        end: "19 Jul",
        images: [],
        pdf: "",
      },
      {
        id: 4,
        month: "Julio",
        week: "Semana 4",
        start: "20 Jul",
        end: "26 Jul",
        images: [],
        pdf: "",
      },
    ],
  },

  {
    id: 2,
    name: "Agosto",
    weeks: [
      {
        id: 5,
        month: "Agosto",
        week: "Semana 5",
        start: "27 Jul",
        end: "2 Ago",
        images: [],
        pdf: "",
      },
      {
        id: 6,
        month: "Agosto",
        week: "Semana 6",
        start: "3 Ago",
        end: "9 Ago",
        images: [],
        pdf: "",
      },
      {
        id: 7,
        month: "Agosto",
        week: "Semana 7",
        start: "10 Ago",
        end: "16 Ago",
        images: [],
        pdf: "",
      },
      {
        id: 8,
        month: "Agosto",
        week: "Semana 8",
        start: "17 Ago",
        end: "23 Ago",
        images: [],
        pdf: "",
      },
    ],
  },

  {
    id: 3,
    name: "Septiembre",
    weeks: [
      {
        id: 9,
        month: "Septiembre",
        week: "Semana 9",
        start: "24 Ago",
        end: "30 Ago",
        images: [],
        pdf: "",
      },
      {
        id: 10,
        month: "Septiembre",
        week: "Semana 10",
        start: "31 Ago",
        end: "6 Sep",
        images: [],
        pdf: "",
      },
      {
        id: 11,
        month: "Septiembre",
        week: "Semana 11",
        start: "7 Sep",
        end: "13 Sep",
        images: [],
        pdf: "",
      },
      {
        id: 12,
        month: "Septiembre",
        week: "Semana 12",
        start: "14 Sep",
        end: "20 Sep",
        images: [],
        pdf: "",
      },
    ],
  },

  {
    id: 4,
    name: "Octubre",
    weeks: [
      {
        id: 13,
        month: "Octubre",
        week: "Semana 13",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 14,
        month: "Octubre",
        week: "Semana 14",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 15,
        month: "Octubre",
        week: "Semana 15",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 16,
        month: "Octubre",
        week: "Semana 16",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
    ],
  },

  {
    id: 5,
    name: "Noviembre",
    weeks: [
      {
        id: 17,
        month: "Noviembre",
        week: "Semana 17",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 18,
        month: "Noviembre",
        week: "Semana 18",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 19,
        month: "Noviembre",
        week: "Semana 19",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 20,
        month: "Noviembre",
        week: "Semana 20",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
    ],
  },

  {
    id: 6,
    name: "Diciembre",
    weeks: [
      {
        id: 21,
        month: "Diciembre",
        week: "Semana 21",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 22,
        month: "Diciembre",
        week: "Semana 22",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 23,
        month: "Diciembre",
        week: "Semana 23",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 24,
        month: "Diciembre",
        week: "Semana 24",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
    ],
  },
    {
    id: 7,
    name: "Enero",
    weeks: [
      {
        id: 25,
        month: "Enero",
        week: "Semana 25",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 26,
        month: "Enero",
        week: "Semana 26",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 27,
        month: "Enero",
        week: "Semana 27",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 28,
        month: "Enero",
        week: "Semana 28",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
    ],
  },

  {
    id: 8,
    name: "Febrero",
    weeks: [
      {
        id: 29,
        month: "Febrero",
        week: "Semana 29",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 30,
        month: "Febrero",
        week: "Semana 30",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 31,
        month: "Febrero",
        week: "Semana 31",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 32,
        month: "Febrero",
        week: "Semana 32",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
    ],
  },

  {
    id: 9,
    name: "Marzo",
    weeks: [
      {
        id: 33,
        month: "Marzo",
        week: "Semana 33",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 34,
        month: "Marzo",
        week: "Semana 34",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 35,
        month: "Marzo",
        week: "Semana 35",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 36,
        month: "Marzo",
        week: "Semana 36",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
    ],
  },

  {
    id: 10,
    name: "Abril",
    weeks: [
      {
        id: 37,
        month: "Abril",
        week: "Semana 37",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 38,
        month: "Abril",
        week: "Semana 38",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 39,
        month: "Abril",
        week: "Semana 39",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 40,
        month: "Abril",
        week: "Semana 40",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
    ],
  },

  {
    id: 11,
    name: "Mayo",
    weeks: [
      {
        id: 41,
        month: "Mayo",
        week: "Semana 41",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 42,
        month: "Mayo",
        week: "Semana 42",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 43,
        month: "Mayo",
        week: "Semana 43",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 44,
        month: "Mayo",
        week: "Semana 44",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
    ],
  },

  {
    id: 12,
    name: "Junio",
    weeks: [
      {
        id: 45,
        month: "Junio",
        week: "Semana 45",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 46,
        month: "Junio",
        week: "Semana 46",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 47,
        month: "Junio",
        week: "Semana 47",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 48,
        month: "Junio",
        week: "Semana 48",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 49,
        month: "Junio",
        week: "Semana 49",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 50,
        month: "Junio",
        week: "Semana 50",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 51,
        month: "Junio",
        week: "Semana 51",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
      {
        id: 52,
        month: "Junio",
        week: "Semana 52",
        start: "",
        end: "",
        images: [],
        pdf: "",
      },
    ],
  },
];